// src/renderer/components/task/VTasks.tsx
import { useEffect, useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import { css } from "styled-system/css";

import { TaskStatusWithIndex } from "@/commons/datas/task";

import VTask from "@/renderer/components/task/VTask";
import { appButtonStyle } from "@/renderer/components/shared/controlStyles";
import { IPC } from "@/renderer/libs/ipc";
import * as Cursor from "@/renderer/utils/cursor";

const rootStyle = css({
  display: "flex",
  height: "100%",
  flexDirection: "column",
  textAlign: "center",
});

const tasksStyle = css({
  flex: 1,
  width: "100%",
  maxHeight: "512px",
  overflowX: "hidden",
  overflowY: "auto",
  padding: "px1",
});

const actionStyle = css({
  display: "flex",
  justifyContent: "center",
});

export default function VTasks() {
  const { t } = useTranslation();
  const [taskStatuses, setTaskStatuses] = useState<{ [key: string]: TaskStatusWithIndex }>({});

  useEffect(() => {
    let mounted = true;
    void IPC.tasks.getStatus().then((statuses) => {
      if (mounted) {
        setTaskStatuses(statuses);
      }
    });

    const subscription = IPC.tasks.on("status", (_event, tasks) => {
      setTaskStatuses(tasks);
      if (Object.values(tasks).some((task) => task.status !== "complete" && task.status !== "failed")) {
        Cursor.setCursor("wait");
      } else {
        Cursor.setDefaultCursor();
      }
    });

    return () => {
      mounted = false;
      subscription.off();
      Cursor.setDefaultCursor();
    };
  }, []);

  const taskStatusArray = useMemo(() => {
    return Object.keys(taskStatuses)
      .reverse()
      .map((id) => ({
        status: { id, ...taskStatuses[id] },
      }));
  }, [taskStatuses]);

  const closable =
    taskStatusArray.length > 0 &&
    Object.values(taskStatuses).filter((status) => status.status === "complete" || status.status === "failed").length ===
      taskStatusArray.length;

  function close() {
    void IPC.tasks.confirmFailed(Object.keys(taskStatuses));
  }

  return (
    <div className={rootStyle}>
      <div className={tasksStyle}>
        {taskStatusArray.map((task) => (
          <VTask key={task.status.id} taskStatus={task.status} />
        ))}
      </div>
      <div className={actionStyle}>
        {closable ? (
          <button className={appButtonStyle} onClick={close} tabIndex={-1} type="button">
            {t("commons.closeButton")}
          </button>
        ) : null}
      </div>
    </div>
  );
}

// src/rendererProcess/components/task/VTasks.vue
<template>
  <VModal
    :visible="visible"
    :center="true"
    :visibleCloseButton="false"
  >
    <t-tasks-root>
      <t-tasks>
        <VTask
          v-for="t in taskStatusArray"
          :key="t.id"
          :taskId="t.id"
          :taskStatus="t.status"
        />
      </t-tasks>
      <button
        tabindex="-1"
        @click="close"
        v-if="closable">
        {{$t("shared.closeButton")}}
      </button>
    </t-tasks-root>
  </VModal>
</template>

<script lang="ts">
// Vue
import { Options, Vue } from "vue-class-component";
import { Prop, Ref, Watch } from "vue-property-decorator";
// Components
import VModal from "@/rendererProcess/components/modal/VModal.vue";
import VProgressBar from "@/rendererProcess/components/utils/VProgressBar.vue";
import VTask from "@/rendererProcess/components/task/VTask.vue";
// Others
import { API } from "@/rendererProcess/api";
import { TaskStatus } from "@/commons/api/interfaces/task";
@Options({
  components: {
    VModal,
    VTask,
    VProgressBar
  },
  emits: []
})
export default class VTasks extends Vue {
  taskStatuses: {[key: string]: TaskStatus} = {};
  mounted() {
    API.on("taskStatus", (e, id, task) => {
      this.taskStatuses[id] = task;
      if (task.status == "complete") {
        window.setTimeout(() => {
          delete this.taskStatuses[id];
        }, 200);
      }
    });
  }
  get taskStatusArray() {
    return Object.keys(this.taskStatuses).reverse().map((id) => ({
      id,
      status: this.taskStatuses[id]
    }))
  }
  get visible() {
    return this.taskStatusArray.length > 0 && (this.$focusedWindows.focused || !this.$focusedWindows.activeOtherMainWindows);
  }
  get closable() {
    return Object.values(this.taskStatuses).filter((status) => {
      return status.status == "complete" || status.status === "failed";
    }).length == this.taskStatusArray.length;
  }
  close() {
    Object.keys(this.taskStatuses).filter((id) => this.taskStatuses[id]?.status === "failed").forEach((key) => {
      delete this.taskStatuses[key];
    });
  }
}
</script>

<style lang="scss" scoped>
t-tasks-root {
  text-align: center;
  display: block;
  >t-tasks {
    width: 100%;
    max-height: 512px;
    overflow-x: hidden;
    overflow-y: auto;
    padding: 4px;
    display: block;
  }
}
</style>
