// src/rendererProcess/components/capture/VCapture.vue
<template>
  <t-details-root
    ref="detailsRoot"
    :style="{
      zIndex: zIndex,
    }"
  >
    <!-- <select v-model="currentSource">
      <option v-for="source in sources" :key="source.id" :value="source">{{ source.name }}</option>
    </select> -->
    <t-video>
      <VDragView
        v-if="currentSource?.size"
        :contentWidth="currentSource.size.width"
        :contentHeight="currentSource.size.height"
      >
        <video ref="video"></video>
      </VDragView>
    </t-video>
    <t-thumbnails
      ><img
        v-for="source in sources"
        :key="source.id"
        :src="source.thumbnailDataURL"
        @click="currentSource = source"
        :class="{
          selected: source === currentSource,
        }"
        draggable="false"
      />
    </t-thumbnails>
  </t-details-root>
</template>

<script setup lang="ts">
// Vue
import { IPC } from "@/rendererProcess/ipc";
import { ref, onMounted, watch } from "vue";
import { MediaSourceInfo } from "@/commons/datas/mediaSourceInfo";
import VDragView from "@/rendererProcess/components/utils/VDragView.vue";
// const props =
defineProps<{
  zIndex: number;
}>();
const detailsRoot = ref<HTMLElement>();
const video = ref<HTMLVideoElement>();
const sources = ref<MediaSourceInfo[]>([]);
const currentSource = ref<MediaSourceInfo>();
const mediaStream = ref<MediaStream>();
onMounted(async () => {
  sources.value = await IPC.send("getMediaSources");
  currentSource.value = sources.value[0];
});
function stopSource() {
  if (mediaStream.value === undefined) {
    return;
  }
  try {
    mediaStream.value.getVideoTracks().forEach((track) => {
      track.stop();
    });
  } catch {
    //
  }
}
async function changeSource() {
  stopSource();
  if (currentSource.value === undefined) {
    return;
  }
  console.log("change source:", currentSource.value);
  mediaStream.value = await navigator.mediaDevices.getUserMedia({
    audio: false,
    video: {
      mandatory: {
        chromeMediaSource: "desktop",
        chromeMediaSourceId: currentSource.value.id,
        maxFrameRate: 60,
        minWidth: currentSource.value.size?.width,
        minHeight: currentSource.value.size?.height,
      },
    },
    /* eslint-disable-next-line @typescript-eslint/no-explicit-any */
  } as any);
  if (video.value !== undefined) {
    video.value.srcObject = mediaStream.value;
    video.value.play();
  }
}
watch(currentSource, changeSource);
</script>

<style lang="scss" scoped>
t-details-root {
  position: relative;
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: column;
  background-image: url("~@/@assets/transparentBackground.png");
  overflow: hidden;
  > input {
    display: block;
  }
  > t-video {
    display: block;
    flex: 1;
    overflow: hidden;
  }
  video {
    width: 100%;
    height: 100%;
  }
  > t-thumbnails {
    background-color: var(--color-0);
    display: flex;
    justify-content: center;
    align-items: center;
    padding: var(--px-2);
    height: 128px;
    > img {
      height: 100%;
      display: block;
      margin-right: var(--px-2);
      cursor: pointer;
      border-radius: var(--rounded);
      overflow: hidden;
      filter: brightness(0.5);
      &.selected {
        filter: brightness(1);
      }
    }
  }
}
</style>

// src/renderer/components/capture/VCapture.tsx
import { useEffect, useRef, useState } from "react";
import { css, cx } from "styled-system/css";

import { MediaSourceInfo } from "@/commons/datas/mediaSourceInfo";

import VDragView from "@/renderer/components/commons/utils/dragView/VDragView";
import { IPC } from "@/renderer/libs/ipc";

const rootStyle = css({
  position: "relative",
  zIndex: 1,
  display: "flex",
  width: "100%",
  height: "100%",
  flexDirection: "column",
  overflow: "hidden",
});

const videoAreaStyle = css({
  flex: 1,
  overflow: "hidden",
});

const videoStyle = css({
  width: "100%",
  height: "100%",
});

const thumbnailsStyle = css({
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  height: "128px",
  backgroundColor: "surface",
  padding: "px2",
});

const thumbnailStyle = css({
  display: "block",
  height: "100%",
  marginRight: "px2",
  overflow: "hidden",
  borderRadius: "window",
  cursor: "pointer",
  filter: "brightness(0.5)",
});

const selectedThumbnailStyle = css({
  filter: "brightness(1)",
});

export default function VCapture() {
  const videoRef = useRef<HTMLVideoElement>(null);
  const [sources, setSources] = useState<MediaSourceInfo[]>([]);
  const [currentSource, setCurrentSource] = useState<MediaSourceInfo | undefined>(undefined);
  const [mediaStream, setMediaStream] = useState<MediaStream | null>(null);

  useEffect(() => {
    let mounted = true;
    void IPC.common.getMediaSources().then((value) => {
      if (mounted) {
        setSources(value);
        setCurrentSource(value[0]);
      }
    });
    return () => {
      mounted = false;
    };
  }, []);

  useEffect(() => {
    return () => {
      stopStream(mediaStream);
    };
  }, [mediaStream]);

  useEffect(() => {
    if (!currentSource) {
      return;
    }

    let active = true;
    const previousStream = mediaStream;
    stopStream(previousStream);

    void navigator.mediaDevices
      .getUserMedia({
        audio: false,
        video: {
          mandatory: {
            chromeMediaSource: "desktop",
            chromeMediaSourceId: currentSource.id,
            maxFrameRate: 60,
            minWidth: currentSource.size?.width,
            minHeight: currentSource.size?.height,
          },
        },
      } as never)
      .then((stream) => {
        if (!active) {
          stopStream(stream);
          return;
        }
        setMediaStream(stream);
        if (videoRef.current) {
          videoRef.current.srcObject = stream;
          void videoRef.current.play();
        }
      })
      .catch(() => {
        if (active) {
          setMediaStream(null);
        }
      });

    return () => {
      active = false;
    };
  }, [currentSource]);

  return (
    <div className={rootStyle}>
      <div className={videoAreaStyle}>
        {currentSource?.size ? (
          <VDragView
            contentHeight={currentSource.size.height}
            contentWidth={currentSource.size.width}>
            <video className={videoStyle} ref={videoRef} />
          </VDragView>
        ) : null}
      </div>
      <div className={thumbnailsStyle}>
        {sources.map((source) => (
          <img
            className={cx(thumbnailStyle, source === currentSource && selectedThumbnailStyle)}
            draggable={false}
            key={source.id}
            onClick={() => setCurrentSource(source)}
            src={source.thumbnailDataURL}
          />
        ))}
      </div>
    </div>
  );
}

function stopStream(stream: MediaStream | null) {
  if (!stream) {
    return;
  }
  try {
    stream.getVideoTracks().forEach((track) => {
      track.stop();
    });
  } catch {
    //
  }
}
