// src/renderer/components/VWindowDetails.vue
<template>
  <e-window-root>
    <e-top>
      <VTitleBar :title="t('titles.details')"> </VTitleBar>
      <VHeaderBar> </VHeaderBar>
    </e-top>
    <e-content>
      <e-board v-if="petaFile">
        <VDetails :peta-file="petaFile" :z-index="1" />
      </e-board>
      <e-property>
        <VProperty :peta-files="singlePetaFiles" @select-tag="() => {}" />
      </e-property>
    </e-content>
    <VContextMenu :z-index="4" />
    <VTooltip :z-index="3" />
  </e-window-root>
</template>

<script setup lang="ts">
import { computed, onMounted, ref, watch } from "vue";
import { useI18n } from "vue-i18n";

import VHeaderBar from "@/renderer/components/commons/headerBar/VHeaderBar.vue";
import VProperty from "@/renderer/components/commons/property/VProperty.vue";
import VTitleBar from "@/renderer/components/commons/titleBar/VTitleBar.vue";
import VContextMenu from "@/renderer/components/commons/utils/contextMenu/VContextMenu.vue";
import VTooltip from "@/renderer/components/commons/utils/tooltip/VTooltip.vue";
import VDetails from "@/renderer/components/details/VDetails.vue";

// import { AnimatedGIFLoader } from "@/renderer/libs/pixi-gif";
import { IPC } from "@/renderer/libs/ipc";
import { Keyboards } from "@/renderer/libs/keyboards";
import { useAppInfoStore } from "@/renderer/stores/appInfoStore/useAppInfoStore";
import { useComponentsStore } from "@/renderer/stores/componentsStore/useComponentsStore";
import { usePetaFilesStore } from "@/renderer/stores/petaFilesStore/usePetaFilesStore";
import { useWindowNameStore } from "@/renderer/stores/windowNameStore/useWindowNameStore";
import { useWindowTitleStore } from "@/renderer/stores/windowTitleStore/useWindowTitleStore";

const appInfoStore = useAppInfoStore();
const { t } = useI18n();
const petaFilesStore = usePetaFilesStore();
const windowNameStore = useWindowNameStore();
const windowTitleStore = useWindowTitleStore();
const petaFileId = ref<string>();
const keyboards = new Keyboards();
onMounted(async () => {
  // AnimatedGIFLoader.add?.();
  petaFilesStore.onUpdate(async (newPetaFiles, mode) => {
    // if (mode === "update") {
    //   vPetaBoard.value?.orderPIXIRender();
    // } else if (mode === "remove") {
    //   newPetaFiles.forEach((petaFile) => {
    //     if (!board.value) {
    //       return;
    //     }
    //     Object.values(board.value.petaPanels).forEach((petaPanel) => {
    //       if (petaPanel.petaFileId === petaFile.id) {
    //         IPC.windows.windowClose();
    //       }
    //     });
    //   });
    // }
  });
  IPC.on("detailsPetaFile", (event, petaFile) => {
    petaFileId.value = petaFile.id;
  });
  petaFileId.value = (await IPC.details.getDetailsPetaFile())?.id;
  keyboards.enabled = true;
  keyboards.keys("Escape").up(() => {
    IPC.windows.windowClose();
  });
});
const petaFile = computed(() => {
  return petaFilesStore.getPetaFile(petaFileId.value);
});
const singlePetaFiles = computed(() => {
  if (petaFile.value === undefined) {
    return [];
  }
  return [petaFile.value];
});
watch(
  () => `${t(`titles.${windowNameStore.windowName.value}`)} - ${appInfoStore.state.value.name}`,
  (value) => {
    windowTitleStore.windowTitle.value = value;
  },
  { immediate: true },
);
</script>

<style lang="scss" scoped>
e-window-root {
  > e-content {
    display: flex;
    padding: 0px;
    > e-board {
      display: block;
      flex: 1;
      z-index: 1;
      cursor: grab;
      background-image: url("/images/textures/transparent.png");
      background-repeat: repeat;
      overflow: hidden;
    }
    > e-property {
      display: block;
      z-index: 2;
      background-color: var(--color-0);
      padding: var(--px-2);
      width: 300px;
    }
  }
}
</style>
<style lang="scss">
@import "@/renderer/styles/index.scss";
</style>

// src/renderer/components/VWindowDetails.tsx
import { useEffect, useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import { css } from "styled-system/css";

import { PetaFile } from "@/commons/datas/petaFile";

import VProperty from "@/renderer/components/commons/property/VProperty";
import VHeaderBar from "@/renderer/components/commons/headerBar/VHeaderBar";
import VTitleBar from "@/renderer/components/commons/titleBar/VTitleBar";
import VDetails from "@/renderer/components/details/VDetails";
import { IPC } from "@/renderer/libs/ipc";
import { Keyboards } from "@/renderer/libs/keyboards";
import { useAppInfoStore } from "@/renderer/stores/appInfoStore/useAppInfoStore";
import { useWindowTitleStore } from "@/renderer/stores/windowTitleStore/useWindowTitleStore";

const rootStyle = css({
  position: "fixed",
  inset: 0,
  display: "flex",
  flexDirection: "column",
  backgroundColor: "surface",
  color: "text",
});

const contentStyle = css({
  display: "flex",
  flex: 1,
  overflow: "hidden",
  padding: 0,
});

const boardStyle = css({
  flex: 1,
  overflow: "hidden",
});

const propertyStyle = css({
  zIndex: 1,
  width: "320px",
  borderLeftWidth: "window",
  borderLeftStyle: "solid",
  borderLeftColor: "border",
  backgroundColor: "surface",
  padding: "px2",
});

export default function VWindowDetails() {
  const { t } = useTranslation();
  const appInfoStore = useAppInfoStore();
  const { windowTitle } = useWindowTitleStore();
  const [petaFile, setPetaFile] = useState<PetaFile>();
  const appName = appInfoStore.state.value.name;
  const title = useMemo(() => t("titles.details"), [t]);

  useEffect(() => {
    windowTitle.value = `${title} - ${appName}`;
  }, [appName, title, windowTitle]);

  useEffect(() => {
    const keyboards = new Keyboards();
    keyboards.enabled = true;
    keyboards.keys("Escape").up(() => {
      void IPC.windows.close();
    });
    return () => {
      keyboards.destroy();
    };
  }, []);

  useEffect(() => {
    let mounted = true;
    void IPC.details.get().then((value) => {
      if (mounted) {
        setPetaFile(value);
      }
    });

    const detailsSubscription = IPC.common.on("detailsPetaFile", (_event, nextPetaFile) => {
      setPetaFile(nextPetaFile);
    });
    const petaFilesSubscription = IPC.petaFiles.on("update", (_event, updatedPetaFiles, mode) => {
      setPetaFile((current) => {
        if (current === undefined) {
          return current;
        }
        const next = updatedPetaFiles.find((item) => item.id === current.id);
        if (next !== undefined) {
          return next;
        }
        if (mode === "remove") {
          return undefined;
        }
        return current;
      });
    });

    return () => {
      mounted = false;
      detailsSubscription.off();
      petaFilesSubscription.off();
    };
  }, []);

  return (
    <div className={rootStyle}>
      <div>
        <VTitleBar title={title} />
        <VHeaderBar />
      </div>
      <div className={contentStyle}>
        <div className={boardStyle}>
          <VDetails petaFile={petaFile} />
        </div>
        <div className={propertyStyle}>
          <VProperty onPetaFileChange={setPetaFile} petaFile={petaFile} />
        </div>
      </div>
    </div>
  );
}
