// src/renderer/components/VWindowSettings.vue
<template>
  <e-root>
    <e-content>
      <e-top>
        <VTitleBar :title="t('titles.settings')"> </VTitleBar>
      </e-top>
      <e-browser>
        <VSettings />
      </e-browser>
    </e-content>
    <VContextMenu :z-index="4" />
  </e-root>
</template>

<script setup lang="ts">
import { onMounted, watch } from "vue";
import { useI18n } from "vue-i18n";

import VTitleBar from "@/renderer/components/commons/titleBar/VTitleBar.vue";
import VContextMenu from "@/renderer/components/commons/utils/contextMenu/VContextMenu.vue";
import VSettings from "@/renderer/components/settings/VSettings.vue";

import { IPC } from "@/renderer/libs/ipc";
import { useAppInfoStore } from "@/renderer/stores/appInfoStore/useAppInfoStore";
import { useKeyboardsStore } from "@/renderer/stores/keyboardsStore/useKeyboardsStore";
import { useWindowNameStore } from "@/renderer/stores/windowNameStore/useWindowNameStore";
import { useWindowTitleStore } from "@/renderer/stores/windowTitleStore/useWindowTitleStore";

const { t } = useI18n();
const keyboards = useKeyboardsStore();
const windowNameStore = useWindowNameStore();
const windowTitleStore = useWindowTitleStore();
const appInfoStore = useAppInfoStore();
onMounted(() => {
  keyboards.enabled = true;
  keyboards.keys("Escape").up(() => {
    IPC.send("windowClose");
  });
});
watch(
  () => `${t(`titles.${windowNameStore.windowName.value}`)} - ${appInfoStore.state.value.name}`,
  (value) => {
    windowTitleStore.windowTitle.value = value;
  },
  { immediate: true },
);
</script>

<style lang="scss" scoped>
e-root {
  background-color: var(--color-0);
  color: var(--color-font);
  > e-content {
    position: fixed;
    top: 0px;
    left: 0px;
    display: flex;
    height: 100%;
    width: 100%;
    flex-direction: column;
    > e-top {
      display: block;
      width: 100%;
      z-index: 2;
    }
    > e-browser {
      display: block;
      overflow: hidden;
      padding: var(--px-3);
      background-color: var(--color-0);
      flex: 1;
      z-index: 1;
    }
    > e-modals {
      position: absolute;
      width: 100%;
      height: 100%;
      top: 0px;
      left: 0px;
      z-index: 3;
    }
  }
}
</style>
<style lang="scss">
@import "@/renderer/styles/index.scss";
</style>

// src/renderer/components/VWindowSettings.tsx
import { useEffect, useMemo } from "react";
import { useTranslation } from "react-i18next";
import { css } from "styled-system/css";

import VTitleBar from "@/renderer/components/commons/titleBar/VTitleBar";
import VSettings from "@/renderer/components/settings/VSettings";
import { IPC } from "@/renderer/libs/ipc";
import { Keyboards } from "@/renderer/libs/keyboards";
import { useAppInfoStore } from "@/renderer/stores/appInfoStore/useAppInfoStore";
import { useWindowTitleStore } from "@/renderer/stores/windowTitleStore/useWindowTitleStore";

const rootStyle = css({
  position: "fixed",
  inset: 0,
  display: "flex",
  flexDirection: "column",
  backgroundColor: "surface",
  color: "text",
});

const contentStyle = css({
  flex: 1,
  overflow: "hidden",
  padding: "px2",
});

export default function VWindowSettings() {
  const { t } = useTranslation();
  const appInfoStore = useAppInfoStore();
  const { windowTitle } = useWindowTitleStore();
  const appName = appInfoStore.state.value.name;
  const title = useMemo(() => t("titles.settings"), [t]);

  useEffect(() => {
    windowTitle.value = `${title} - ${appName}`;
  }, [appName, title, windowTitle]);

  useEffect(() => {
    const keyboards = new Keyboards();
    keyboards.enabled = true;
    keyboards.keys("Escape").up(() => {
      void IPC.windows.close();
    });
    return () => {
      keyboards.destroy();
    };
  }, []);

  return (
    <div className={rootStyle}>
      <div>
        <VTitleBar title={title} />
      </div>
      <div className={contentStyle}>
        <VSettings />
      </div>
    </div>
  );
}
