// src/renderer/components/VWindowEula.tsx
import { useEffect, useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import { css } from "styled-system/css";

import { EULA } from "@/commons/defines";
import { Settings } from "@/commons/datas/settings";

import { WindowScaffold } from "@/renderer/components/shared/WindowScaffold";
import { appButtonStyle } from "@/renderer/components/shared/controlStyles";
import { IPC } from "@/renderer/libs/ipc";

const bodyStyle = css({
  display: "block",
  userSelect: "text",
  whiteSpace: "pre-wrap",
});

const buttonsStyle = css({
  display: "flex",
  justifyContent: "center",
  flexWrap: "wrap",
  marginTop: "px2",
});

export default function VWindowEula() {
  const { t } = useTranslation();
  const [settings, setSettings] = useState<Settings | null>(null);

  useEffect(() => {
    let mounted = true;
    void IPC.settings.get().then((value) => {
      if (mounted) {
        setSettings(value);
      }
    });

    const subscription = IPC.settings.on("update", (_event, value) => {
      setSettings(value);
    });

    return () => {
      mounted = false;
      subscription.off();
    };
  }, []);

  const needToAgree = useMemo(() => {
    return settings !== null ? settings.eula !== EULA : false;
  }, [settings]);

  return (
    <WindowScaffold>
      <div className={bodyStyle}>{t("eula.body")}</div>
      <div className={buttonsStyle}>
        {needToAgree ? (
          <>
            <button className={appButtonStyle} onClick={() => IPC.common.eula(true)} type="button">
              {t("eula.agree")}
            </button>
            <button className={appButtonStyle} onClick={() => IPC.common.eula(false)} type="button">
              {t("eula.disagree")}
            </button>
          </>
        ) : (
          <button className={appButtonStyle} onClick={() => IPC.windows.close()} type="button">
            {t("commons.closeButton")}
          </button>
        )}
      </div>
    </WindowScaffold>
  );
}

// src/renderer/components/VWindowEula.vue
<template>
  <e-window-root>
    <e-top>
      <VTitleBar :title="t('titles.eula')"> </VTitleBar>
    </e-top>
    <e-content>
      <e-body>{{ t("eula.body") }}</e-body>
      <e-buttons v-if="needToAgree">
        <button @click="agree">{{ t("eula.agree") }}</button>
        <button @click="disagree">{{ t("eula.disagree") }}</button>
      </e-buttons>
      <e-buttons v-else>
        <button @click="close">{{ t("commons.closeButton") }}</button>
      </e-buttons>
    </e-content>
    <VContextMenu :z-index="4" />
    <VTooltip :z-index="3" />
  </e-window-root>
</template>

<script setup lang="ts">
import { computed, watch } from "vue";
import { useI18n } from "vue-i18n";

import VTitleBar from "@/renderer/components/commons/titleBar/VTitleBar.vue";
import VContextMenu from "@/renderer/components/commons/utils/contextMenu/VContextMenu.vue";
import VTooltip from "@/renderer/components/commons/utils/tooltip/VTooltip.vue";

import { EULA } from "@/commons/defines";

import { IPC } from "@/renderer/libs/ipc";
import { useAppInfoStore } from "@/renderer/stores/appInfoStore/useAppInfoStore";
import { useSettingsStore } from "@/renderer/stores/settingsStore/useSettingsStore";
import { useWindowNameStore } from "@/renderer/stores/windowNameStore/useWindowNameStore";
import { useWindowTitleStore } from "@/renderer/stores/windowTitleStore/useWindowTitleStore";

const { t } = useI18n();
const appInfoStore = useAppInfoStore();
const settings = useSettingsStore();
const windowNameStore = useWindowNameStore();
const windowTitleStore = useWindowTitleStore();
function agree() {
  IPC.common.eula(true);
}
function disagree() {
  IPC.common.eula(false);
}
function close() {
  IPC.windows.close();
}
const needToAgree = computed(() => {
  return settings.state.value.eula !== EULA;
});
watch(
  () => `${t(`titles.${windowNameStore.windowName.value}`)} - ${appInfoStore.state.value.name}`,
  (value) => {
    windowTitleStore.windowTitle.value = value;
  },
  { immediate: true },
);
</script>

<style lang="scss" scoped>
e-window-root {
  > e-content {
    > e-body {
      display: block;
      user-select: text;
      white-space: pre-wrap;
    }
    > e-buttons {
      display: block;
      text-align: center;
    }
  }
}
</style>
<style lang="scss">
@import "@/renderer/styles/index.scss";
</style>
