// src/renderer/components/VWindowPassword.vue
<template>
  <form>
    <e-window-root>
      <e-top>
        <VTitleBar :title="''"> </VTitleBar>
      </e-top>
      <e-content>
        <input type="password" v-model="password" />
        <button type="submit" @click.prevent="login">login</button>
        <VCheckbox v-model:value="save" />
      </e-content>
    </e-window-root>
  </form>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { useI18n } from "vue-i18n";

import VCheckbox from "./commons/utils/checkbox/VCheckbox.vue";
import VTitleBar from "@/renderer/components/commons/titleBar/VTitleBar.vue";

import { IPC } from "@/renderer/libs/ipc";
import { useWindowTitleStore } from "@/renderer/stores/windowTitleStore/useWindowTitleStore";

const { t } = useI18n();
const windowTitleStore = useWindowTitleStore();
const password = ref<string>("");
const save = ref<boolean>(false);
onMounted(async () => {
  windowTitleStore.windowTitle.value = "";
});
function login() {
  IPC.common.login(password.value, save.value);
  // IPC.windows.windowClose();
}
</script>

<style lang="scss" scoped>
e-window-root {
  > e-content {
    display: flex;
    flex-direction: column;
  }
}
</style>
<style lang="scss">
@import "@/renderer/styles/index.scss";
</style>

// src/renderer/components/VWindowPassword.tsx
import { FormEvent, useEffect, useState } from "react";
import { css } from "styled-system/css";

import VTitleBar from "@/renderer/components/commons/titleBar/VTitleBar";
import VCheckbox from "@/renderer/components/commons/utils/checkbox/VCheckbox";
import { appButtonStyle, textInputStyle } from "@/renderer/components/shared/controlStyles";
import { IPC } from "@/renderer/libs/ipc";
import { useWindowTitleStore } from "@/renderer/stores/windowTitleStore/useWindowTitleStore";

const rootStyle = css({
  position: "fixed",
  inset: 0,
  display: "flex",
  flexDirection: "column",
  backgroundColor: "surface",
  color: "text",
});

const contentStyle = css({
  display: "flex",
  flex: 1,
  flexDirection: "column",
  gap: "px2",
  padding: "px2",
});

const rowStyle = css({
  display: "flex",
  alignItems: "center",
  gap: "px2",
});

export default function VWindowPassword() {
  const { windowTitle } = useWindowTitleStore();
  const [password, setPassword] = useState("");
  const [save, setSave] = useState(false);

  useEffect(() => {
    windowTitle.value = "";
  }, [windowTitle]);

  function login(event: FormEvent) {
    event.preventDefault();
    void IPC.common.login(password, save);
  }

  return (
    <form className={rootStyle} onSubmit={login}>
      <div>
        <VTitleBar title="" />
      </div>
      <div className={contentStyle}>
        <input
          autoFocus
          className={textInputStyle}
          onChange={(event) => setPassword(event.target.value)}
          type="password"
          value={password}
        />
        <div>
          <button className={appButtonStyle} type="submit">
            login
          </button>
        </div>
        <div className={rowStyle}>
          <VCheckbox onValueChange={setSave} value={save} />
        </div>
      </div>
    </form>
  );
}
