// src/renderer/components/settings/VSettingsDatas.tsx
import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { css } from "styled-system/css";

import { Settings } from "@/commons/datas/settings";

import VTextarea from "@/renderer/components/commons/utils/textarea/VTextarea";
import { appButtonStyle } from "@/renderer/components/shared/controlStyles";
import { IPC } from "@/renderer/libs/ipc";

const rootStyle = css({
  display: "flex",
  flexDirection: "column",
  gap: "px1",
});

const descriptionStyle = css({
  marginBottom: "px2",
  color: "text",
  opacity: 0.72,
});

export default function VSettingsDatas({
  settings,
}: {
  onSettingsChange: (settings: Settings) => void;
  settings: Settings;
}) {
  const { t } = useTranslation();
  const [tempPetaFileDirectory, setTempPetaFileDirectory] = useState("");

  useEffect(() => {
    setTempPetaFileDirectory(settings.petaFileDirectory.path);
  }, [settings.petaFileDirectory.path]);

  async function changePetaFileDirectory() {
    const result = await IPC.modals.open(
      t("settings.changePetaFileDirectoryDialog", [tempPetaFileDirectory]),
      [t("commons.yes"), t("commons.no")],
    );
    if (result === 0) {
      const changed = await IPC.common.changePetaFileDirectory(tempPetaFileDirectory);
      if (!changed) {
        await IPC.modals.open(
          t("settings.changePetaFileDirectoryErrorDialog", [tempPetaFileDirectory]),
          [t("commons.yes")],
        );
        setTempPetaFileDirectory(settings.petaFileDirectory.path);
      }
    } else {
      setTempPetaFileDirectory(settings.petaFileDirectory.path);
    }
  }

  async function browsePetaFileDirectory() {
    const path = await IPC.common.browsePetaFileDirectory();
    if (path) {
      setTempPetaFileDirectory(path);
    }
  }

  return (
    <div className={rootStyle}>
      <div>
        <button className={appButtonStyle} onClick={() => void browsePetaFileDirectory()} type="button">
          {t("settings.browsePetaFileDirectoryButton")}
        </button>
      </div>
      <VTextarea
        clickToEdit
        onValueChange={setTempPetaFileDirectory}
        outerStyle={{ width: "100%" }}
        textAreaStyle={{ width: "100%" }}
        trim
        type="single"
        value={tempPetaFileDirectory}
      />
      <div>
        <button
          className={appButtonStyle}
          disabled={tempPetaFileDirectory === ""}
          onClick={() => void changePetaFileDirectory()}
          type="button">
          {t("settings.changePetaFileDirectoryButton")}
        </button>
      </div>
      <p className={descriptionStyle}>{t("settings.changePetaFileDirectoryDescriptions")}</p>
    </div>
  );
}

// src/renderer/components/settings/VSettingsDatas.vue
<template>
  <e-settings-content-root>
    <button @click="browsePetaFileDirectory">
      {{ t("settings.browsePetaFileDirectoryButton") }}</button
    ><br />
    <VTextarea
      :type="'single'"
      :click-to-edit="true"
      :trim="true"
      :text-area-style="{ width: '100%' }"
      :outer-style="{ width: '100%' }"
      :value="tempPetaFileDirectory"
      @update:value="(value) => (tempPetaFileDirectory = value)" />
    <br />
    <button @click="changePetaFileDirectory" :disabled="tempPetaFileDirectory === ''">
      {{ t("settings.changePetaFileDirectoryButton") }}
    </button>
    <p>{{ t("settings.changePetaFileDirectoryDescriptions") }}</p>
  </e-settings-content-root>
</template>

<script setup lang="ts">
import { onMounted, ref, watch } from "vue";
import { useI18n } from "vue-i18n";

import VTextarea from "@/renderer/components/commons/utils/textarea/VTextarea.vue";

import { IPC } from "@/renderer/libs/ipc";
import { useComponentsStore } from "@/renderer/stores/componentsStore/useComponentsStore";
import { useSettingsStore } from "@/renderer/stores/settingsStore/useSettingsStore";

const settingsStore = useSettingsStore();
const components = useComponentsStore();
const { t } = useI18n();
const tempPetaFileDirectory = ref("");
onMounted(() => {
  restorePetaFileDirectory();
});
async function changePetaFileDirectory() {
  const result = await IPC.modals.openModal(
    t("settings.changePetaFileDirectoryDialog", [tempPetaFileDirectory.value]),
    [t("commons.yes"), t("commons.no")],
  );
  if (result === 0) {
    if (!(await IPC.common.changePetaFileDirectory(tempPetaFileDirectory.value))) {
      await IPC.modals.openModal(
        t("settings.changePetaFileDirectoryErrorDialog", [tempPetaFileDirectory.value]),
        [t("commons.yes")],
      );
      restorePetaFileDirectory();
    }
  } else {
    restorePetaFileDirectory();
  }
}
function restorePetaFileDirectory() {
  tempPetaFileDirectory.value = settingsStore.state.value.petaFileDirectory.path;
}
async function browsePetaFileDirectory() {
  const path = await IPC.common.browsePetaFileDirectory();
  if (path) {
    tempPetaFileDirectory.value = path;
  }
}
watch(
  () => settingsStore.state.value.petaFileDirectory.path,
  () => {
    restorePetaFileDirectory();
  },
);
</script>

<style lang="scss" scoped></style>
<style lang="scss" scoped>
@import "@/renderer/components/settings/index.scss";
</style>
