// src/renderer/components/settings/VSettingsWeb.vue
<template>
  <e-settings-content-root>
    <label>
      <VCheckbox v-model:value="settingsStore.state.value.web" />
      {{ t("settings.web") }}
    </label>
    <p>{{ t("settings.webDescriptions", [WEBHOOK_PORT]) }}</p>
  </e-settings-content-root>
</template>

<script setup lang="ts">
import { useI18n } from "vue-i18n";

import VCheckbox from "@/renderer/components/commons/utils/checkbox/VCheckbox.vue";

import { WEBHOOK_PORT } from "@/commons/defines";

import { useSettingsStore } from "@/renderer/stores/settingsStore/useSettingsStore";

const settingsStore = useSettingsStore();
const { t } = useI18n();
</script>

<style lang="scss" scoped></style>
<style lang="scss" scoped>
@import "@/renderer/components/settings/index.scss";
</style>

// src/renderer/components/settings/VSettingsWeb.tsx
import { useTranslation } from "react-i18next";
import { css } from "styled-system/css";

import { WEBHOOK_PORT } from "@/commons/defines";
import { Settings } from "@/commons/datas/settings";

import VCheckbox from "@/renderer/components/commons/utils/checkbox/VCheckbox";

const rootStyle = css({
  display: "flex",
  flexDirection: "column",
  gap: "px1",
});

const labelStyle = css({
  display: "flex",
  alignItems: "center",
  gap: "px1",
});

const descriptionStyle = css({
  marginBottom: "px2",
  color: "text",
  opacity: 0.72,
});

export default function VSettingsWeb({
  onSettingsChange,
  settings,
}: {
  onSettingsChange: (settings: Settings) => void;
  settings: Settings;
}) {
  const { t } = useTranslation();

  return (
    <div className={rootStyle}>
      <label className={labelStyle}>
        <VCheckbox onValueChange={(web) => onSettingsChange({ ...settings, web })} value={settings.web} />
        {t("settings.web")}
      </label>
      <p className={descriptionStyle}>{t("settings.webDescriptions", [WEBHOOK_PORT])}</p>
    </div>
  );
}
