// src/renderer/components/settings/VSettingsUpdate.tsx
import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { css } from "styled-system/css";

import { URL_DOWNLOAD } from "@/commons/defines";

import { appButtonStyle } from "@/renderer/components/shared/controlStyles";
import { IPC } from "@/renderer/libs/ipc";
import { useAppInfoStore } from "@/renderer/stores/appInfoStore/useAppInfoStore";

const rootStyle = css({
  display: "block",
  textAlign: "center",
});

const paragraphStyle = css({
  fontSize: "size1",
  wordBreak: "break-word",
});

export default function VSettingsUpdate() {
  const { t } = useTranslation();
  const appInfoStore = useAppInfoStore();
  const appInfo = appInfoStore.state.value;
  const [updateAvailable, setUpdateAvailable] = useState(false);
  const [latestVersion, setLatestVersion] = useState("1.1.1");

  useEffect(() => {
    void checkUpdate();
  }, []);

  async function checkUpdate() {
    const remoteBinaryInfo = await IPC.common.getLatestVersion();
    setLatestVersion(remoteBinaryInfo.version);
    setUpdateAvailable(!remoteBinaryInfo.isLatest);
  }

  function downloadUpdate() {
    void IPC.common.openURL(`${URL_DOWNLOAD}${latestVersion}`);
  }

  function releaseNote() {
    void IPC.common.openURL(`${URL_DOWNLOAD}${appInfo.version}`);
  }

  return (
    <div className={rootStyle}>
      {updateAvailable ? (
        <div>
          <p className={paragraphStyle}>{t("settings.updateAvailable")}</p>
          <p className={paragraphStyle}>
            {t("settings.currentVersion")}: {appInfo.version}
          </p>
          <p className={paragraphStyle}>
            {t("settings.latestVersion")}: {latestVersion}
          </p>
          <p>
            <button className={appButtonStyle} onClick={downloadUpdate} type="button">
              {t("settings.updateButton")}
            </button>
          </p>
        </div>
      ) : (
        <div>
          <p className={paragraphStyle}>{t("settings.thisIsLatest")}</p>
          <p className={paragraphStyle}>
            {t("settings.currentVersion")}: {appInfo.version}
          </p>
          <p>
            <button className={appButtonStyle} onClick={releaseNote} type="button">
              {t("settings.releaseNoteButton")}
            </button>
          </p>
        </div>
      )}
      <button className={appButtonStyle} onClick={() => void checkUpdate()} type="button">
        {t("settings.checkUpdateButton")}
      </button>
    </div>
  );
}

// src/renderer/components/settings/VSettingsUpdate.vue
<template>
  <e-settings-content-root class="update">
    <e-info v-if="updateAvailable">
      <p>
        {{ t("settings.updateAvailable") }}
      </p>
      <p>{{ t("settings.currentVersion") }}: {{ appInfoStore.state.value.version }}</p>
      <p>{{ t("settings.latestVersion") }}: {{ latestVersion }}</p>
      <p>
        <button @click="downloadUpdate">{{ t("settings.updateButton") }}</button>
      </p>
    </e-info>
    <e-info v-else>
      <p>
        {{ t("settings.thisIsLatest") }}
      </p>
      <p>{{ t("settings.currentVersion") }}: {{ appInfoStore.state.value.version }}</p>
      <p>
        <button @click="releaseNote">{{ t("settings.releaseNoteButton") }}</button>
      </p>
    </e-info>
    <button @click="checkUpdate">{{ t("settings.checkUpdateButton") }}</button>
  </e-settings-content-root>
</template>

<script setup lang="ts">
import { onMounted, ref } from "vue";
import { useI18n } from "vue-i18n";

import { URL_DOWNLOAD } from "@/commons/defines";

import { IPC } from "@/renderer/libs/ipc";
import { useAppInfoStore } from "@/renderer/stores/appInfoStore/useAppInfoStore";

const { t } = useI18n();
const appInfoStore = useAppInfoStore();
const updateAvailable = ref(false);
const latestVersion = ref("1.1.1");
onMounted(() => {
  checkUpdate();
});
async function checkUpdate() {
  const remoteBinaryInfo = await IPC.common.getLatestVersion();
  latestVersion.value = remoteBinaryInfo.version;
  updateAvailable.value = !remoteBinaryInfo.isLatest;
}
function downloadUpdate() {
  IPC.common.openURL(`${URL_DOWNLOAD}${latestVersion.value}`);
}
function releaseNote() {
  IPC.common.openURL(`${URL_DOWNLOAD}${appInfoStore.state.value.version}`);
}
</script>

<style lang="scss" scoped>
e-settings-content-root.update {
  display: block;
  text-align: center;
  > e-info {
    display: block;
    overflow: hidden;
    > p {
      font-size: var(--size-1);
      word-break: break-word;
    }
  }
}
</style>
<style lang="scss" scoped>
@import "@/renderer/components/settings/index.scss";
</style>
