// src/rendererProcess/components/settings/VSettingsGeneral.vue
<template>
  <t-settings-content-root>
    <label>
      <input
        type="checkbox"
        v-model="settingsStore.state.value.darkMode"
        :disabled="settingsStore.state.value.autoDarkMode"
      />
      {{ t("settings.darkMode") }}
    </label>
    <br />
    <label>
      <input type="checkbox" v-model="settingsStore.state.value.autoDarkMode" />
      {{ t("settings.autoDarkMode") }}
    </label>
    <p>{{ t("settings.autoDarkModeDescriptions") }}</p>
    <label>
      <input type="checkbox" v-model="settingsStore.state.value.alwaysOnTop" />
      {{ t("settings.alwaysOnTop") }}
    </label>
    <p>{{ t("settings.alwaysOnTopDescriptions") }}</p>
    <label>
      <select v-model="settingsStore.state.value.show">
        <option value="board">{{ t("settings.showBoard") }}</option>
        <option value="browser">{{ t("settings.showBrowser") }}</option>
        <option value="both">{{ t("settings.showBoth") }}</option>
      </select>
      {{ t("settings.show") }}
    </label>
    <p>{{ t("settings.showDescriptions") }}</p>
  </t-settings-content-root>
</template>

<script setup lang="ts">
// Others
import { useSettingsStore } from "@/rendererProcess/stores/settingsStore";
import { useI18n } from "vue-i18n";

const settingsStore = useSettingsStore();
const { t } = useI18n();
</script>

<style lang="scss" scoped></style>
<style lang="scss" scoped>
@import "@/rendererProcess/components/settings/index.scss";
</style>

// src/renderer/components/settings/VSettingsGeneral.tsx
import { useMemo } from "react";
import { useTranslation } from "react-i18next";
import { css } from "styled-system/css";

import VCheckbox from "@/renderer/components/commons/utils/checkbox/VCheckbox";
import VSelect from "@/renderer/components/commons/utils/select/VSelect";
import { Settings } from "@/commons/datas/settings";

const rootStyle = css({
  display: "flex",
  flexDirection: "column",
  gap: "px1",
});

const labelStyle = css({
  display: "flex",
  alignItems: "center",
  gap: "px1",
});

const descriptionStyle = css({
  marginBottom: "px2",
  color: "text",
  opacity: 0.72,
});

export default function VSettingsGeneral({
  onSettingsChange,
  settings,
}: {
  onSettingsChange: (settings: Settings) => void;
  settings: Settings;
}) {
  const { t } = useTranslation();

  const showItems = useMemo(
    () => [
      { value: "board", label: t("settings.showBoard") },
      { value: "browser", label: t("settings.showBrowser") },
      { value: "both", label: t("settings.showBoth") },
    ],
    [t],
  );

  return (
    <div className={rootStyle}>
      <label className={labelStyle}>
        <VCheckbox
          disabled={settings.autoDarkMode}
          onValueChange={(darkMode) => onSettingsChange({ ...settings, darkMode })}
          value={settings.darkMode}
        />
        {t("settings.darkMode")}
      </label>
      <label className={labelStyle}>
        <VCheckbox
          onValueChange={(autoDarkMode) => onSettingsChange({ ...settings, autoDarkMode })}
          value={settings.autoDarkMode}
        />
        {t("settings.autoDarkMode")}
      </label>
      <p className={descriptionStyle}>{t("settings.autoDarkModeDescriptions")}</p>
      <label className={labelStyle}>
        <VSelect
          items={showItems}
          onValueChange={(show) => onSettingsChange({ ...settings, show: show as Settings["show"] })}
          value={settings.show}
        />
        {t("settings.show")}
      </label>
      <p className={descriptionStyle}>{t("settings.showDescriptions")}</p>
    </div>
  );
}
