// src/renderer/components/task/VTasks.tsx
import { useEffect, useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import { css } from "styled-system/css";

import { TaskStatusWithIndex } from "@/commons/datas/task";

import VTask from "@/renderer/components/task/VTask";
import { appButtonStyle } from "@/renderer/components/shared/controlStyles";
import { IPC } from "@/renderer/libs/ipc";
import * as Cursor from "@/renderer/utils/cursor";

const rootStyle = css({
  display: "flex",
  height: "100%",
  flexDirection: "column",
  textAlign: "center",
});

const tasksStyle = css({
  flex: 1,
  width: "100%",
  maxHeight: "512px",
  overflowX: "hidden",
  overflowY: "auto",
  padding: "px1",
});

const actionStyle = css({
  display: "flex",
  justifyContent: "center",
});

export default function VTasks() {
  const { t } = useTranslation();
  const [taskStatuses, setTaskStatuses] = useState<{ [key: string]: TaskStatusWithIndex }>({});

  useEffect(() => {
    let mounted = true;
    void IPC.tasks.getStatus().then((statuses) => {
      if (mounted) {
        setTaskStatuses(statuses);
      }
    });

    const subscription = IPC.tasks.on("status", (_event, tasks) => {
      setTaskStatuses(tasks);
      if (Object.values(tasks).some((task) => task.status !== "complete" && task.status !== "failed")) {
        Cursor.setCursor("wait");
      } else {
        Cursor.setDefaultCursor();
      }
    });

    return () => {
      mounted = false;
      subscription.off();
      Cursor.setDefaultCursor();
    };
  }, []);

  const taskStatusArray = useMemo(() => {
    return Object.keys(taskStatuses)
      .reverse()
      .map((id) => ({
        status: { id, ...taskStatuses[id] },
      }));
  }, [taskStatuses]);

  const closable =
    taskStatusArray.length > 0 &&
    Object.values(taskStatuses).filter((status) => status.status === "complete" || status.status === "failed").length ===
      taskStatusArray.length;

  function close() {
    void IPC.tasks.confirmFailed(Object.keys(taskStatuses));
  }

  return (
    <div className={rootStyle}>
      <div className={tasksStyle}>
        {taskStatusArray.map((task) => (
          <VTask key={task.status.id} taskStatus={task.status} />
        ))}
      </div>
      <div className={actionStyle}>
        {closable ? (
          <button className={appButtonStyle} onClick={close} tabIndex={-1} type="button">
            {t("commons.closeButton")}
          </button>
        ) : null}
      </div>
    </div>
  );
}

// src/renderer/components/task/VTasks.vue
<template>
  <e-tasks-root>
    <e-tasks>
      <VTask
        v-for="t in taskStatusArray"
        :key="t.status.id"
        :task-id="t.status.id"
        :task-status="t.status" />
    </e-tasks>
    <button tabindex="-1" @click="close" v-if="closable">
      {{ t("commons.closeButton") }}
    </button>
  </e-tasks-root>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { useI18n } from "vue-i18n";

import VTask from "@/renderer/components/task/VTask.vue";

import { TaskStatusWithIndex } from "@/commons/datas/task";

import { IPC } from "@/renderer/libs/ipc";
import * as Cursor from "@/renderer/utils/cursor";

const { t } = useI18n();
const taskStatuses = ref<{ [key: string]: TaskStatusWithIndex }>({});
onMounted(async () => {
  taskStatuses.value = await IPC.tasks.getStatus();
  IPC.tasks.on("status", (e, tasks) => {
    taskStatuses.value = tasks;
    if (
      Object.values(tasks).find((t) => t.status !== "complete" && t.status !== "failed") !==
      undefined
    ) {
      Cursor.setCursor("wait");
    } else {
      Cursor.setDefaultCursor();
    }
  });
});
const taskStatusArray = computed(() => {
  return Object.keys(taskStatuses.value)
    .reverse()
    .map((id) => ({
      status: { id, ...taskStatuses.value[id] },
    }));
});

const closable = computed(() => {
  return (
    Object.values(taskStatuses.value).filter((status) => {
      return status.status === "complete" || status.status === "failed";
    }).length === taskStatusArray.value.length
  );
});
function close() {
  IPC.tasks.confirmFailed(Object.keys(taskStatuses.value));
}
</script>

<style lang="scss" scoped>
e-tasks-root {
  display: flex;
  flex-direction: column;
  height: 100%;
  text-align: center;
  > e-tasks {
    display: block;
    flex: 1;
    padding: var(--px-1);
    width: 100%;
    max-height: 512px;
    overflow-x: hidden;
    overflow-y: auto;
  }
}
</style>
