// src/rendererProcess/components/top/VTitleBar.vue
<template>
  <t-titlebar-root>
    <t-title>
      <t-icon>{{ title }}</t-icon>
    </t-title>
    <t-content>
      <t-top>
        <!-- -->
      </t-top>
      <t-bottom>
        <t-draggable
          class="left"
          :class="{
            mac: systemInfo.platform === 'darwin',
          }"
        >
        </t-draggable>
        <slot></slot>
        <t-draggable class="right"> </t-draggable>
      </t-bottom>
    </t-content>
    <t-window-buttons v-if="!isMac">
      <t-window-button v-if="resizable" @click="minimizeWindow">
        <t-icon>&#xe921;</t-icon>
      </t-window-button>
      <t-window-button v-if="resizable" @click="maximizeWindow">
        <t-icon>&#xe922;</t-icon>
      </t-window-button>
      <t-window-button class="close" @click="closeWindow">
        <t-icon>&#xe8bb;</t-icon>
      </t-window-button>
    </t-window-buttons>
  </t-titlebar-root>
</template>

<script setup lang="ts">
// Vue
import { computed } from "vue";
// Components
// Others
import { API } from "@/rendererProcess/api";
import { WindowType } from "@/commons/datas/windowType";
import { useWindowTypeStore } from "@/rendererProcess/stores/windowTypeStore";
import { useSystemInfoStore } from "@/rendererProcess/stores/systemInfoStore";
const { windowType } = useWindowTypeStore();
const { systemInfo } = useSystemInfoStore();
defineProps<{
  title?: string;
}>();

function minimizeWindow() {
  API.send("windowMinimize");
}
function maximizeWindow() {
  API.send("windowMaximize");
}
function closeWindow() {
  API.send("windowClose");
}
const resizable = computed(() => {
  return windowType.value !== WindowType.SETTINGS;
});
const isMac = computed(() => {
  return systemInfo.value.platform === "darwin";
});
</script>

<style lang="scss" scoped>
t-titlebar-root {
  --tab-height: 24px;
  --top-draggable-height: 10px;
  background-color: var(--color-1);
  min-height: var(--tab-height);
  display: flex;
  position: relative;
  > t-title {
    position: absolute;
    height: 100%;
    width: 100%;
    display: flex;
    align-items: center;
    pointer-events: none;
    > t-icon {
      width: 100%;
      text-align: center;
      display: inline-block;
      font-size: var(--size-0);
    }
  }
  > t-content {
    flex-grow: 1;
    overflow: hidden;
    display: flex;
    flex-direction: column;
    > t-top {
      flex-grow: 1;
      -webkit-app-region: drag;
      display: block;
      height: var(--top-draggable-height);
    }
    > t-bottom {
      display: flex;
      flex-direction: row;
      > t-draggable {
        -webkit-app-region: drag;
        display: block;
        &.left {
          flex-grow: 0;
          width: calc(var(--tab-height) + var(--top-draggable-height));
          &.mac {
            width: calc(var(--tab-height) + var(--top-draggable-height) + 32px);
          }
        }
        &.right {
          flex-grow: 1;
          -webkit-app-region: drag;
        }
      }
    }
  }
  > t-window-buttons {
    display: flex;
    > t-window-button {
      display: flex;
      padding: 0px 16px;
      align-items: center;
      > t-icon {
        display: inline-block;
        font-size: 6px;
        font-family: Segoe MDL2 Assets;
      }
      &:hover {
        background-color: var(--color-2);
        &.close {
          color: var(--color-window-button);
          background-color: var(--window-buttons-close-hover);
        }
      }
    }
  }
}
</style>

// src/renderer/components/commons/titleBar/VTitleBar.tsx
import { CSSProperties, PropsWithChildren } from "react";
import { css, cx } from "styled-system/css";

import { IPC } from "@/renderer/libs/ipc";
import { useSystemInfoStore } from "@/renderer/stores/systemInfoStore/useSystemInfoStore";
import { useWindowNameStore } from "@/renderer/stores/windowNameStore/useWindowNameStore";

const rootStyle = css({
  position: "relative",
  display: "flex",
  minHeight: "tabHeight",
  backgroundColor: "surfaceMuted",
});

const titleStyle = css({
  pointerEvents: "none",
  position: "absolute",
  inset: 0,
  display: "flex",
  alignItems: "center",
});

const titleTextStyle = css({
  display: "inline-block",
  width: "100%",
  textAlign: "center",
  fontSize: "size0",
});

const contentStyle = css({
  display: "flex",
  flex: 1,
  flexDirection: "column",
  overflow: "hidden",
});

const topDragStyle = css({
  display: "block",
  flexGrow: 1,
  height: "topDraggableHeight",
});

const bottomStyle = css({
  display: "flex",
  flexDirection: "row",
});

const dragBaseStyle = css({
  display: "block",
});

const leftDragStyle = css({
  flexGrow: 0,
  width: "calc(var(--tab-height) + var(--top-draggable-height))",
});

const leftDragMacStyle = css({
  width: "calc(var(--tab-height) + var(--top-draggable-height) + 32px)",
});

const rightDragStyle = css({
  flexGrow: 1,
});

const buttonsStyle = css({
  display: "flex",
});

const buttonStyle = css({
  display: "flex",
  alignItems: "center",
  border: "none",
  margin: 0,
  background: "transparent",
  paddingX: "16px",
  color: "inherit",
  _hover: {
    backgroundColor: "surfaceEmphasis",
  },
});

const closeButtonStyle = css({
  _hover: {
    backgroundColor: "closeHover",
    color: "windowButton",
  },
});

const iconStyle = css({
  display: "inline-block",
  fontSize: "6px",
  fontFamily: "Segoe MDL2 Assets",
});

const dragRegionStyle = {
  WebkitAppRegion: "drag",
} as CSSProperties;

export default function VTitleBar({
  title,
  hideControls = false,
  children,
}: PropsWithChildren<{
  title?: string;
  hideControls?: boolean;
}>) {
  const { windowName } = useWindowNameStore();
  const { systemInfo } = useSystemInfoStore();
  const resizable = windowName.value !== "settings";
  const isMac = systemInfo.value.platform === "darwin";

  return (
    <div className={rootStyle}>
      <div className={titleStyle}>
        <div className={titleTextStyle}>{title}</div>
      </div>
      <div className={contentStyle}>
        <div className={topDragStyle} style={dragRegionStyle} />
        <div className={bottomStyle}>
          <div className={cx(dragBaseStyle, leftDragStyle, isMac && leftDragMacStyle)} style={dragRegionStyle} />
          {children}
          <div className={cx(dragBaseStyle, rightDragStyle)} style={dragRegionStyle} />
        </div>
      </div>
      {!isMac && !hideControls ? (
        <div className={buttonsStyle}>
          {resizable ? (
            <button className={buttonStyle} onClick={() => IPC.windows.minimize()} type="button">
              <span className={iconStyle}>&#xe921;</span>
            </button>
          ) : null}
          {resizable ? (
            <button className={buttonStyle} onClick={() => IPC.windows.maximize()} type="button">
              <span className={iconStyle}>&#xe922;</span>
            </button>
          ) : null}
          <button
            className={cx(buttonStyle, closeButtonStyle)}
            onClick={() => IPC.windows.close()}
            type="button">
            <span className={iconStyle}>&#xe8bb;</span>
          </button>
        </div>
      ) : null}
    </div>
  );
}
