// src/renderer/components/utils/VDragView.vue
<template>
  <t-drag-view-root ref="detailsRoot">
    <t-img
      :style="{
        transform: `translate(${position.x + stageRect.x / 2}px, ${
          position.y + stageRect.y / 2
        }px) scale(${scale})`,
        width: `${contentWidth}px`,
        height: `${contentHeight}px`,
      }"
    >
      <slot></slot>
    </t-img>
  </t-drag-view-root>
</template>

<script setup lang="ts">
// Vue
import { BOARD_ZOOM_MAX, BOARD_ZOOM_MIN } from "@/commons/defines";
import { resizeImage } from "@/commons/utils/resizeImage";
import { Vec2, vec2FromPointerEvent } from "@/commons/utils/vec2";
import { useResizerStore } from "@/renderer/stores/resizerStore/useResizerStore";
import { useSettingsStore } from "@/renderer/stores/settingsStore/useSettingsStore";
import { useSystemInfoStore } from "@/renderer/stores/systemInfoStore/useSystemInfoStore";
import { ref, onMounted, onUnmounted, watch, computed } from "vue";
// Components
const props = defineProps<{
  contentWidth: number;
  contentHeight: number;
}>();
const detailsRoot = ref<HTMLElement>();
const mouseOffset = new Vec2();
const stageRect = ref(new Vec2());
const { systemInfo } = useSystemInfoStore();
const scale = ref(1);
const position = ref(new Vec2());
const settingsStore = useSettingsStore();
const resizerStore = useResizerStore();
const pointerPosition = new Vec2();
const dragging = ref(false);
let fitToOutside = true;
onMounted(() => {
  detailsRoot.value?.addEventListener("mousewheel", wheel as (e: Event) => void);
  detailsRoot.value?.addEventListener("pointerdown", pointerdown);
  detailsRoot.value?.addEventListener("dblclick", reset);
  window.addEventListener("pointerup", pointerup);
  window.addEventListener("pointermove", pointermove);
  resizerStore.on("resize", resize);
  resizerStore.observe(detailsRoot.value);
  if (detailsRoot.value !== undefined) {
    resize(detailsRoot.value.getBoundingClientRect());
  }
});
onUnmounted(() => {
  detailsRoot.value?.removeEventListener("mousewheel", wheel as (e: Event) => void);
  detailsRoot.value?.removeEventListener("pointerdown", pointerdown);
  window.removeEventListener("pointerup", pointerup);
  window.removeEventListener("pointermove", pointermove);
});
function resize(rect: DOMRect | DOMRectReadOnly) {
  mouseOffset.set(detailsRoot.value?.getBoundingClientRect());
  stageRect.value.set(rect.width, rect.height);
  if (fitToOutside) {
    reset();
  }
  constraint();
}
function reset() {
  fitToOutside = true;
  scale.value = defaultScale.value;
  position.value.x = (-props.contentWidth * defaultScale.value) / 2;
  position.value.y = (-props.contentHeight * defaultScale.value) / 2;
}
function pointerdown(event: PointerEvent) {
  pointerPosition.set(vec2FromPointerEvent(event));
  dragging.value = true;
}
function pointerup() {
  dragging.value = false;
}
function pointermove(event: PointerEvent) {
  if (!dragging.value) {
    return;
  }
  fitToOutside = false;
  const p = vec2FromPointerEvent(event);
  const vec = p.clone().sub(pointerPosition);
  position.value.add(vec);
  pointerPosition.set(p);
  constraint();
}
function constraint() {
  // 左側がはみ出たら修正
  if (position.value.x + stageRect.value.x / 2 > 0) {
    position.value.x = -stageRect.value.x / 2;
  }
  // 右がはみ出たら修正
  if (
    props.contentWidth * scale.value +
      position.value.x +
      stageRect.value.x / 2 -
      stageRect.value.x <
    0
  ) {
    position.value.x =
      -props.contentWidth * scale.value - (stageRect.value.x / 2 - stageRect.value.x);
  }
  // 上がはみ出たら修正
  if (position.value.y + stageRect.value.y / 2 > 0) {
    position.value.y = -stageRect.value.y / 2;
  }
  // 下がはみ出たら修正
  if (
    props.contentHeight * scale.value +
      position.value.y +
      stageRect.value.y / 2 -
      stageRect.value.y <
    0
  ) {
    position.value.y =
      -props.contentHeight * scale.value - (stageRect.value.y / 2 - stageRect.value.y);
  }
  // 左右がはみ出たら中心へ
  if (props.contentWidth * scale.value < stageRect.value.x) {
    position.value.x = (-props.contentWidth * scale.value) / 2;
  }
  // 上下がはみ出たら中心へ
  if (props.contentHeight * scale.value < stageRect.value.y) {
    position.value.y = (-props.contentHeight * scale.value) / 2;
  }
}
function wheel(event: WheelEvent) {
  const mouse = vec2FromPointerEvent(event).sub(mouseOffset).sub(stageRect.value.clone().div(2));
  if (event.ctrlKey || systemInfo.value.platform === "win32") {
    const currentZoom = scale.value;
    scale.value *= 1 + -event.deltaY * settingsStore.state.value.zoomSensitivity * 0.00001;
    if (scale.value > BOARD_ZOOM_MAX) {
      scale.value = BOARD_ZOOM_MAX;
    }
    if (scale.value < BOARD_ZOOM_MIN) {
      scale.value = BOARD_ZOOM_MIN;
    }
    position.value
      .mult(-1)
      .add(mouse)
      .mult(scale.value / currentZoom)
      .sub(mouse)
      .mult(-1);
  } else {
    position.value.add(
      new Vec2(event.deltaX, event.deltaY)
        .mult(settingsStore.state.value.moveSensitivity)
        .mult(-0.01),
    );
  }
  fitToOutside = false;
  constraint();
}
const defaultScale = computed(() => {
  let width = 0;
  let height = 0;
  const maxWidth = stageRect.value.x * 1;
  const maxHeight = stageRect.value.y * 1;
  if (props.contentHeight / props.contentWidth < maxHeight / maxWidth) {
    const size = resizeImage(props.contentWidth, props.contentHeight, maxWidth, "width");
    width = size.width;
    height = size.height;
  } else {
    const size = resizeImage(props.contentWidth, props.contentHeight, maxHeight, "height");
    height = size.height;
    width = size.width;
  }
  height;
  return width / props.contentWidth;
});
watch([() => props.contentWidth, () => props.contentHeight], () => {
  reset();
});
</script>

<style lang="scss" scoped>
t-drag-view-root {
  position: relative;
  width: 100%;
  height: 100%;
  display: block;
  background-image: url("~@/@assets/transparentBackground.png");
  overflow: hidden;
  > t-img {
    display: block;
    position: absolute;
    transform-origin: top left;
    overflow: hidden;
  }
}
</style>

// src/renderer/components/commons/utils/dragView/VDragView.tsx
import { PropsWithChildren, useCallback, useEffect, useRef, useState } from "react";
import { css } from "styled-system/css";

import { BOARD_ZOOM_MAX, BOARD_ZOOM_MIN } from "@/commons/defines";
import { Settings } from "@/commons/datas/settings";
import { resizeImage } from "@/commons/utils/resizeImage";
import { Vec2, vec2FromPointerEvent } from "@/commons/utils/vec2";

import TransparentTexture from "@/_public/images/textures/transparent.png";
import { IPC } from "@/renderer/libs/ipc";
import { useSystemInfoStore } from "@/renderer/stores/systemInfoStore/useSystemInfoStore";

const rootStyle = css({
  position: "relative",
  display: "block",
  width: "100%",
  height: "100%",
  overflow: "hidden",
});

const contentStyle = css({
  position: "absolute",
  display: "block",
  overflow: "hidden",
  transformOrigin: "top left",
});

type ViewState = {
  scale: number;
  positionX: number;
  positionY: number;
  stageWidth: number;
  stageHeight: number;
};

export default function VDragView({
  children,
  contentWidth,
  contentHeight,
}: PropsWithChildren<{
  contentWidth: number;
  contentHeight: number;
}>) {
  const { systemInfo } = useSystemInfoStore();
  const rootRef = useRef<HTMLDivElement>(null);
  const [settings, setSettings] = useState<Settings | null>(null);
  const [viewState, setViewState] = useState<ViewState>({
    scale: 1,
    positionX: 0,
    positionY: 0,
    stageWidth: 0,
    stageHeight: 0,
  });
  const stageRectRef = useRef(new Vec2());
  const mouseOffsetRef = useRef(new Vec2());
  const pointerPositionRef = useRef(new Vec2());
  const positionRef = useRef(new Vec2());
  const scaleRef = useRef(1);
  const draggingRef = useRef(false);
  const fitToOutsideRef = useRef(true);
  const settingsRef = useRef<Settings | null>(null);

  const commit = useCallback(() => {
    setViewState({
      scale: scaleRef.current,
      positionX: positionRef.current.x,
      positionY: positionRef.current.y,
      stageWidth: stageRectRef.current.x,
      stageHeight: stageRectRef.current.y,
    });
  }, []);

  const getDefaultScale = useCallback(() => {
    const maxWidth = stageRectRef.current.x;
    const maxHeight = stageRectRef.current.y;
    if (contentWidth === 0 || contentHeight === 0 || maxWidth === 0 || maxHeight === 0) {
      return 1;
    }
    if (contentHeight / contentWidth < maxHeight / maxWidth) {
      return resizeImage(contentWidth, contentHeight, maxWidth, "width").width / contentWidth;
    }
    return resizeImage(contentWidth, contentHeight, maxHeight, "height").width / contentWidth;
  }, [contentHeight, contentWidth]);

  const constraint = useCallback(() => {
    if (positionRef.current.x + stageRectRef.current.x / 2 > 0) {
      positionRef.current.x = -stageRectRef.current.x / 2;
    }
    if (
      contentWidth * scaleRef.current +
        positionRef.current.x +
        stageRectRef.current.x / 2 -
        stageRectRef.current.x <
      0
    ) {
      positionRef.current.x =
        -contentWidth * scaleRef.current - (stageRectRef.current.x / 2 - stageRectRef.current.x);
    }
    if (positionRef.current.y + stageRectRef.current.y / 2 > 0) {
      positionRef.current.y = -stageRectRef.current.y / 2;
    }
    if (
      contentHeight * scaleRef.current +
        positionRef.current.y +
        stageRectRef.current.y / 2 -
        stageRectRef.current.y <
      0
    ) {
      positionRef.current.y =
        -contentHeight * scaleRef.current -
        (stageRectRef.current.y / 2 - stageRectRef.current.y);
    }
    if (contentWidth * scaleRef.current < stageRectRef.current.x) {
      positionRef.current.x = (-contentWidth * scaleRef.current) / 2;
    }
    if (contentHeight * scaleRef.current < stageRectRef.current.y) {
      positionRef.current.y = (-contentHeight * scaleRef.current) / 2;
    }
  }, [contentHeight, contentWidth]);

  const reset = useCallback(() => {
    fitToOutsideRef.current = true;
    scaleRef.current = getDefaultScale();
    positionRef.current.x = (-contentWidth * scaleRef.current) / 2;
    positionRef.current.y = (-contentHeight * scaleRef.current) / 2;
    commit();
  }, [commit, contentHeight, contentWidth, getDefaultScale]);

  const resize = useCallback(
    (rect: DOMRectReadOnly) => {
      if (rootRef.current) {
        mouseOffsetRef.current.set(rootRef.current.getBoundingClientRect());
      }
      stageRectRef.current.set(rect.width, rect.height);
      if (fitToOutsideRef.current) {
        reset();
      }
      constraint();
      commit();
    },
    [commit, constraint, reset],
  );

  useEffect(() => {
    settingsRef.current = settings;
  }, [settings]);

  useEffect(() => {
    let mounted = true;
    void IPC.settings.get().then((value) => {
      if (mounted) {
        setSettings(value);
      }
    });
    const settingsSubscription = IPC.settings.on("update", (_event, value) => {
      setSettings(value);
    });
    return () => {
      mounted = false;
      settingsSubscription.off();
    };
  }, []);

  useEffect(() => {
    const root = rootRef.current;
    if (!root) {
      return;
    }

    const resizeObserver = new ResizeObserver((entries) => {
      const rect = entries[0]?.contentRect;
      if (rect) {
        resize(rect);
      }
    });

    const pointerDown = (event: PointerEvent) => {
      pointerPositionRef.current.set(vec2FromPointerEvent(event));
      draggingRef.current = true;
    };
    const pointerUp = () => {
      draggingRef.current = false;
    };
    const pointerMove = (event: PointerEvent) => {
      if (!draggingRef.current) {
        return;
      }
      fitToOutsideRef.current = false;
      const current = vec2FromPointerEvent(event);
      const diff = current.clone().sub(pointerPositionRef.current);
      positionRef.current.add(diff);
      pointerPositionRef.current.set(current);
      constraint();
      commit();
    };
    const wheel = (event: WheelEvent) => {
      event.preventDefault();
      const activeSettings = settingsRef.current;
      if (!activeSettings) {
        return;
      }
      const mouse = vec2FromPointerEvent(event)
        .sub(mouseOffsetRef.current)
        .sub(stageRectRef.current.clone().div(2));

      if (event.ctrlKey || systemInfo.value.platform === "win32") {
        const currentZoom = scaleRef.current;
        scaleRef.current *= 1 + -event.deltaY * activeSettings.zoomSensitivity * 0.00001;
        if (scaleRef.current > BOARD_ZOOM_MAX) {
          scaleRef.current = BOARD_ZOOM_MAX;
        }
        if (scaleRef.current < BOARD_ZOOM_MIN) {
          scaleRef.current = BOARD_ZOOM_MIN;
        }
        positionRef.current
          .mult(-1)
          .add(mouse)
          .mult(scaleRef.current / currentZoom)
          .sub(mouse)
          .mult(-1);
      } else {
        positionRef.current.add(
          new Vec2(event.deltaX, event.deltaY)
            .mult(activeSettings.moveSensitivity)
            .mult(-0.01),
        );
      }
      fitToOutsideRef.current = false;
      constraint();
      commit();
    };

    root.addEventListener("pointerdown", pointerDown);
    root.addEventListener("dblclick", reset);
    root.addEventListener("wheel", wheel, { passive: false });
    window.addEventListener("pointerup", pointerUp);
    window.addEventListener("pointermove", pointerMove);
    resizeObserver.observe(root);
    resize(root.getBoundingClientRect());

    return () => {
      resizeObserver.disconnect();
      root.removeEventListener("pointerdown", pointerDown);
      root.removeEventListener("dblclick", reset);
      root.removeEventListener("wheel", wheel);
      window.removeEventListener("pointerup", pointerUp);
      window.removeEventListener("pointermove", pointerMove);
    };
  }, [commit, constraint, reset, resize, systemInfo.value.platform]);

  useEffect(() => {
    reset();
  }, [contentHeight, contentWidth, reset]);

  return (
    <div
      className={rootStyle}
      ref={rootRef}
      style={{ backgroundImage: `url(${TransparentTexture})` }}>
      <div
        className={contentStyle}
        style={{
          transform: `translate(${viewState.positionX + viewState.stageWidth / 2}px, ${
            viewState.positionY + viewState.stageHeight / 2
          }px) scale(${viewState.scale})`,
          width: `${contentWidth}px`,
          height: `${contentHeight}px`,
        }}>
        {children}
      </div>
    </div>
  );
}
