// src/renderer/components/board/VBoardProperty.vue
<template>
  <e-board-property-root>
    <button tabindex="-1" @click="scale = 1">{{ scale.toFixed(2) }}x</button>
    <input type="color" v-model="fillColor" tabindex="-1" ref="inputFillColor" />
    <input type="color" v-model="lineColor" tabindex="-1" ref="inputLineColor" />
  </e-board-property-root>
</template>

<script setup lang="ts">
import { computed, ref } from "vue";

import { RPetaBoard } from "@/commons/datas/rPetaBoard";

const props = defineProps<{
  board: RPetaBoard;
}>();
const emit = defineEmits<{
  (e: "update", board: RPetaBoard): void;
}>();
const inputFillColor = ref<HTMLInputElement>();
const inputLineColor = ref<HTMLInputElement>();
const fillColor = computed({
  get() {
    return props.board.background.fillColor;
  },
  set(value) {
    emit("update", {
      ...props.board,
      background: {
        ...props.board.background,
        fillColor: value,
      },
    });
  },
});
const lineColor = computed({
  get() {
    return props.board.background.lineColor;
  },
  set(value) {
    emit("update", {
      ...props.board,
      background: {
        ...props.board.background,
        lineColor: value,
      },
    });
  },
});
const scale = computed({
  get() {
    return props.board.transform.scale;
  },
  set(value) {
    emit("update", {
      ...props.board,
      transform: {
        ...props.board.transform,
        scale: value,
      },
    });
  },
});
</script>

<style lang="scss" scoped>
e-board-property-root {
  position: absolute;
  top: 0px;
  left: 0px;
  height: 100%;
  width: 100%;
  padding: var(--px-1);
  align-items: center;
  justify-content: center;
  display: flex;
  > button {
    min-width: 24px;
    padding: 0px;
    height: 100%;
    min-width: 50px;
    &.color {
      border-radius: var(--rounded);
      width: auto;
      min-width: 0px;
      aspect-ratio: 1;
    }
  }
  > * {
    margin: 0px;
    margin-right: var(--px-1);
  }
}
</style>

// src/renderer/components/board/VBoardProperty.tsx
import { css, cx } from "styled-system/css";

import { RPetaBoard } from "@/commons/datas/rPetaBoard";

const rootStyle = css({
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  gap: "px1",
  width: "100%",
  height: "100%",
  paddingX: "px2",
});

const buttonStyle = css({
  minWidth: "56px",
  height: "24px",
  borderWidth: "window",
  borderStyle: "solid",
  borderColor: "border",
  borderRadius: "rounded",
  backgroundColor: "surface",
  color: "text",
  fontSize: "size0",
});

const inputStyle = css({
  width: "32px",
  height: "24px",
  border: "none",
  backgroundColor: "transparent",
  padding: 0,
});

export default function VBoardProperty({
  board,
  onUpdate,
}: {
  board: RPetaBoard;
  onUpdate: (board: RPetaBoard) => void;
}) {
  return (
    <div className={rootStyle}>
      <button
        className={buttonStyle}
        onClick={() =>
          onUpdate({
            ...board,
            transform: {
              ...board.transform,
              scale: 1,
            },
          })
        }
        tabIndex={-1}
        type="button">
        {board.transform.scale.toFixed(2)}x
      </button>
      <input
        aria-label="board fill color"
        className={cx(buttonStyle, inputStyle)}
        onChange={(event) =>
          onUpdate({
            ...board,
            background: {
              ...board.background,
              fillColor: event.target.value,
            },
          })
        }
        tabIndex={-1}
        type="color"
        value={board.background.fillColor}
      />
      <input
        aria-label="board line color"
        className={cx(buttonStyle, inputStyle)}
        onChange={(event) =>
          onUpdate({
            ...board,
            background: {
              ...board.background,
              lineColor: event.target.value,
            },
          })
        }
        tabIndex={-1}
        type="color"
        value={board.background.lineColor}
      />
    </div>
  );
}
