// src/renderer/components/commons/utils/textarea/VTextarea.tsx
import Fuse from "fuse.js";
import {
  CSSProperties,
  forwardRef,
  KeyboardEvent,
  MouseEvent,
  MutableRefObject,
  useEffect,
  useImperativeHandle,
  useMemo,
  useRef,
  useState,
} from "react";
import { css, cx } from "styled-system/css";

const rootStyle = css({
  position: "relative",
  display: "inline-block",
  minWidth: "px3",
  width: "100%",
});

const baseFieldStyle = css({
  display: "inline-block",
  width: "100%",
  minHeight: "size2",
  borderRadius: "calc(var(--rounded) / 4)",
  color: "text",
  lineHeight: "size2",
  whiteSpace: "pre-wrap",
  wordBreak: "break-word",
  outline: "none",
});

const idleStyle = css({
  cursor: "pointer",
});

const editingStyle = css({
  cursor: "text",
  backgroundColor: "surface",
});

const outlinedStyle = css({
  boxShadow: "inset 0 0 0 1px var(--colors-text)",
});

const inputResetStyle = css({
  border: "none",
  background: "transparent",
  resize: "none",
  padding: 0,
  font: "inherit",
});

const complementStyle = css({
  position: "absolute",
  top: "calc(100% + 4px)",
  left: 0,
  zIndex: 10,
  display: "flex",
  flexWrap: "wrap",
  gap: "px1",
  maxWidth: "256px",
  padding: "px2",
  borderWidth: "window",
  borderStyle: "solid",
  borderColor: "border",
  borderRadius: "window",
  backgroundColor: "surface",
  boxShadow: "0 8px 24px rgba(0, 0, 0, 0.2)",
});

const complementItemStyle = css({
  display: "inline-block",
  borderWidth: "window",
  borderStyle: "solid",
  borderColor: "border",
  borderRadius: "window",
  backgroundColor: "surfaceMuted",
  paddingX: "px1",
  paddingY: "px0",
  fontSize: "size0",
  lineHeight: "size1",
  cursor: "pointer",
  userSelect: "none",
  _hover: {
    backgroundColor: "surfaceEmphasis",
  },
});

const selectedComplementItemStyle = css({
  backgroundColor: "surfaceEmphasis",
  borderColor: "accent",
});

export type VTextareaHandle = {
  edit: () => void;
  isEditing: () => boolean;
};

type Props = {
  allowEmpty?: boolean;
  blurToReset?: boolean;
  clickToEdit?: boolean;
  complements?: string[];
  look?: string;
  noOutline?: boolean;
  onDeleteOfEmpty?: () => void;
  onValueChange?: (value: string) => void;
  outerStyle?: CSSProperties;
  readOnly?: boolean;
  textAreaStyle?: CSSProperties;
  trim?: boolean;
  type: "single" | "multi";
  value?: string;
};

function formatValue(value: string, type: Props["type"], trim?: boolean) {
  let nextValue = value;
  if (type === "single") {
    nextValue = nextValue.replace(/\r?\n/g, "");
  }
  if (trim) {
    nextValue = nextValue.trim();
  }
  return nextValue;
}

const VTextarea = forwardRef<VTextareaHandle, Props>(function VTextarea(
  {
    allowEmpty,
    blurToReset,
    clickToEdit,
    complements,
    look,
    noOutline,
    onDeleteOfEmpty,
    onValueChange,
    outerStyle,
    readOnly,
    textAreaStyle,
    trim,
    type,
    value,
  },
  ref,
) {
  const inputRef = useRef<HTMLInputElement | HTMLTextAreaElement | null>(null);
  const [editing, setEditing] = useState(false);
  const [draftValue, setDraftValue] = useState(value ?? "");
  const [selectedIndex, setSelectedIndex] = useState(0);

  useImperativeHandle(ref, () => ({
    edit() {
      if (readOnly) {
        return;
      }
      setEditing(true);
      setDraftValue(value ?? "");
    },
    isEditing() {
      return editing;
    },
  }));

  useEffect(() => {
    if (!editing) {
      setDraftValue(value ?? "");
    }
  }, [editing, value]);

  useEffect(() => {
    if (!editing || inputRef.current === null) {
      return;
    }
    inputRef.current.focus();
    if ("select" in inputRef.current) {
      inputRef.current.select();
    }
  }, [editing]);

  const filteredComplements = useMemo(() => {
    if (!editing || complements === undefined) {
      return [];
    }
    const source = formatValue(draftValue, type, trim);
    if (source === "") {
      return complements;
    }
    const fuse = new Fuse(complements);
    return fuse.search(source).map((result) => result.item);
  }, [complements, draftValue, editing, trim, type]);

  useEffect(() => {
    setSelectedIndex(0);
  }, [draftValue, filteredComplements.length]);

  function restore() {
    setDraftValue(value ?? "");
  }

  function commit(nextValue: string, blur: boolean) {
    if (readOnly) {
      return;
    }
    const formatted = formatValue(nextValue, type, trim);
    if (blur && blurToReset) {
      restore();
      setEditing(false);
      return;
    }
    if (formatted === "") {
      if (!allowEmpty) {
        restore();
        setEditing(false);
        return;
      }
    }
    if (formatted !== formatValue(value ?? "", type, trim)) {
      onValueChange?.(formatted);
    }
    setEditing(false);
  }

  function beginEdit() {
    if (readOnly || editing) {
      return;
    }
    setEditing(true);
    setDraftValue(value ?? "");
  }

  function handleKeyDown(event: KeyboardEvent<HTMLInputElement | HTMLTextAreaElement>) {
    if (!editing) {
      return;
    }
    if ((event.key === "Backspace" || event.key === "Delete") && draftValue === "") {
      onDeleteOfEmpty?.();
    }
    if (event.key === "Escape") {
      event.preventDefault();
      commit(draftValue, true);
      return;
    }
    if (type === "single" && event.key === "Enter") {
      event.preventDefault();
      if (filteredComplements.length > 0 && selectedIndex >= 0) {
        const item = filteredComplements[selectedIndex];
        if (item !== undefined) {
          setDraftValue(item);
          commit(item, false);
          return;
        }
      }
      commit(draftValue, false);
      return;
    }
    if (editing && filteredComplements.length > 0) {
      if (event.key === "ArrowDown" || event.key === "Tab") {
        event.preventDefault();
        setSelectedIndex((current) =>
          filteredComplements.length === 0 ? 0 : (current + 1) % filteredComplements.length,
        );
      } else if (event.key === "ArrowUp") {
        event.preventDefault();
        setSelectedIndex((current) =>
          filteredComplements.length === 0
            ? 0
            : (current - 1 + filteredComplements.length) % filteredComplements.length,
        );
      }
    }
  }

  const displayValue = editing ? formatValue(value ?? "", type, trim) : formatValue(look ?? value ?? "", type, trim);
  const commonClassName = cx(
    baseFieldStyle,
    editing ? editingStyle : idleStyle,
    noOutline === false && editing && outlinedStyle,
  );

  function renderInput() {
    if (type === "multi") {
      return (
        <textarea
          className={cx(commonClassName, inputResetStyle)}
          onBlur={() => commit(draftValue, true)}
          onChange={(event) => setDraftValue(event.target.value)}
          onKeyDown={handleKeyDown}
          ref={inputRef as MutableRefObject<HTMLTextAreaElement | null>}
          spellCheck={false}
          style={textAreaStyle}
          value={draftValue}
        />
      );
    }
    return (
        <input
          className={cx(commonClassName, inputResetStyle)}
        onBlur={() => commit(draftValue, true)}
        onChange={(event) => setDraftValue(event.target.value)}
        onKeyDown={handleKeyDown}
        onPaste={(event) => {
          event.preventDefault();
          const pasted = event.clipboardData.getData("text/plain");
          setDraftValue((current) => `${current}${formatValue(pasted, type, trim)}`);
        }}
          ref={inputRef as MutableRefObject<HTMLInputElement | null>}
        spellCheck={false}
        style={textAreaStyle}
        value={draftValue}
      />
    );
  }

  return (
    <div className={rootStyle} style={outerStyle}>
      {editing ? (
        renderInput()
      ) : (
        <div
          className={commonClassName}
          onClick={() => {
            if (clickToEdit) {
              beginEdit();
            }
          }}
          onDoubleClick={() => beginEdit()}
          onMouseDown={(event: MouseEvent<HTMLDivElement>) => {
            if (readOnly) {
              event.preventDefault();
            }
          }}
          style={textAreaStyle}>
          {displayValue}
        </div>
      )}
      {editing && filteredComplements.length > 0 ? (
        <div className={complementStyle}>
          {filteredComplements.map((item, index) => (
            <button
              className={cx(complementItemStyle, index === selectedIndex && selectedComplementItemStyle)}
              key={item}
              onMouseDown={(event) => {
                event.preventDefault();
                setDraftValue(item);
                commit(item, false);
              }}
              type="button">
              {item}
            </button>
          ))}
        </div>
      ) : null}
    </div>
  );
});

export default VTextarea;

// src/rendererProcess/components/utils/VTextarea.vue
<template>
  <t-textarea-root :style="outerStyle">
    <t-textarea
      lock-keyboard
      ref="textArea"
      v-text="value"
      @input="input(($event.target as HTMLDivElement).innerText)"
      @blur="blur"
      @keypress.enter="enter"
      @keydown.escape="escape"
      @keydown.delete="backspace"
      @paste="paste"
      @dblclick="click('double')"
      @click="click('single')"
      :contenteditable="editing"
      :class="{
        editing: editing,
        outline: props.noOutline === false,
      }"
      spellcheck="false"
      :style="textAreaStyle"
    >
    </t-textarea>
    <VComplement
      v-if="complements"
      :value="rawValue"
      :items="complements"
      @select="inputFromComplement"
      :zIndex="10"
      :editing="editing"
      :textArea="textArea"
    />
  </t-textarea-root>
</template>

<script setup lang="ts">
// Vue
import { ref, watch, onMounted, computed, nextTick } from "vue";
import VComplement from "@/rendererProcess/components/utils/VComplement.vue";
const props = defineProps<{
  value?: string;
  look?: string;
  type: "single" | "multi";
  trim?: boolean;
  textAreaStyle?: Partial<CSSStyleDeclaration>;
  outerStyle?: Partial<CSSStyleDeclaration>;
  allowEmpty?: boolean;
  clickToEdit?: boolean;
  readonly?: boolean;
  complements?: string[];
  blurToReset?: boolean;
  noOutline?: boolean;
}>();
const emit = defineEmits<{
  (e: "update:value", value: string): void;
  (e: "deleteOfEmpty"): void;
}>();
const textArea = ref<HTMLElement>();
const rawValue = ref("");
const editing = ref(false);
onMounted(() => {
  forceResetValue();
  if (props.type === "multi" && props.blurToReset) {
    throw new Error("type = multiとblurToResetは非推奨の組み合わせです。");
  }
});
function input(value: string) {
  if (props.readonly) {
    return;
  }
  rawValue.value = format(value);
}
function inputFromComplement(value: string) {
  input(value);
  end(false);
}
function backspace() {
  if (rawValue.value === "") {
    emit("deleteOfEmpty");
  }
}
function click(type: "single" | "double") {
  if (props.readonly) {
    return;
  }
  if (editing.value) {
    return;
  }
  if (props.clickToEdit === true && type === "single") {
    edit();
  } else if (type === "double") {
    edit();
  }
}
function paste(e: ClipboardEvent) {
  if (props.readonly) {
    return;
  }
  e.preventDefault();
  const value = e.clipboardData?.getData("text/plain");
  if (value !== undefined) {
    document.execCommand("insertText", false, format(value));
  }
}
function end(blur: boolean) {
  if (props.readonly) {
    return;
  }
  if (!editing.value) {
    return;
  }
  if (props.blurToReset && blur) {
    restore();
  } else {
    value.value = rawValue.value;
  }
  editing.value = false;
  textArea.value?.blur();
}
function escape() {
  end(true);
}
function edit() {
  editing.value = true;
  forceResetValue();
  textArea.value?.focus();
  nextTick(() => {
    if (textArea.value) {
      textArea.value.focus();
      const range = document.createRange();
      range.selectNodeContents(textArea.value);
      const sel = window.getSelection();
      sel?.removeAllRanges();
      sel?.addRange(range);
    }
  });
}
function enter(e: KeyboardEvent) {
  if (props.readonly) {
    return;
  }
  if (props.type === "single") {
    e.preventDefault();
    end(false);
  }
}
function format(value: string) {
  if (props.type === "single") {
    value = value.replace(/\r?\n/g, "");
  }
  if (props.trim === true) {
    value = value.trim();
  }
  return value;
}
function forceResetValue() {
  rawValue.value = props.value !== undefined ? props.value : "";
  textArea.value?.scrollTo(0, 0);
}
function blur() {
  end(true);
}
function restore() {
  if (textArea.value) {
    textArea.value.innerText = value.value;
  }
}
const value = computed({
  get() {
    if (editing.value) {
      return format(props.value || "");
    }
    return format(
      props.look !== undefined ? props.look : props.value !== undefined ? props.value : "",
    );
  },
  set(value: string) {
    value = format(value);
    // propsが存在し、値が同じならスキップ
    if (props.value !== undefined && value === format(props.value)) {
      restore();
      return;
    }
    // 値が空で、空を許可されていない場合はスキップ
    if (value === "" && props.allowEmpty !== true) {
      restore();
      return;
    }
    emit("update:value", value);
  },
});
watch(
  () => props.value,
  () => {
    forceResetValue();
  },
);
defineExpose({
  edit,
});
</script>

<style lang="scss" scoped>
t-textarea-root {
  display: inline-block;
  min-width: var(--px2);
  position: relative;
  > t-textarea {
    line-height: var(--size-2);
    min-height: var(--size-2);
    cursor: pointer;
    display: inline-block;
    white-space: pre-wrap;
    word-break: break-word;
    outline: none;
    border-radius: 2px;
    &.editing {
      cursor: unset;
      &.outline {
        outline: solid 2px var(--color-font);
        outline-offset: 1px;
      }
    }
  }
  // &::before {
  //   content: "";
  //   position: absolute;
  //   top: 0px;
  //   left: 0px;
  //   width: 100%;
  //   height: 100%;
  //   border-radius: var(--rounded);
  //   pointer-events: none;
  //   background-color: rgba($color: #ff0000, $alpha: 0.5);
  // }
}
</style>
