// src/renderer/components/commons/headerBar/VHeaderBar.tsx
import { PropsWithChildren, useEffect, useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import { css, cx } from "styled-system/css";

import BrowserIcon from "@/_public/images/icons/browser.png";
import BoardIcon from "@/_public/images/icons/board.png";
import ImportFileIcon from "@/_public/images/icons/importFile.png";
import ImportFolderIcon from "@/_public/images/icons/importFolder.png";
import NSFWIcon from "@/_public/images/icons/nsfw.png";
import SettingsIcon from "@/_public/images/icons/settings.png";
import SFWIcon from "@/_public/images/icons/sfw.png";
import WebIcon from "@/_public/images/icons/web.png";
import { Settings } from "@/commons/datas/settings";

import { appButtonStyle } from "@/renderer/components/shared/controlStyles";
import { IPC } from "@/renderer/libs/ipc";
import { useWindowNameStore } from "@/renderer/stores/windowNameStore/useWindowNameStore";

const rootStyle = css({
  position: "relative",
  zIndex: 2,
  display: "block",
  width: "100%",
  minHeight: "30px",
  backgroundColor: "surface",
});

const shadowStyle = css({
  boxShadow: "0px 1px 1px 0px rgba(0, 0, 0, 0.3)",
});

const leftGroupStyle = css({
  position: "absolute",
  top: 0,
  left: 0,
  display: "flex",
  height: "100%",
  padding: "px1",
  gap: "px1",
});

const rightGroupStyle = css({
  position: "absolute",
  top: 0,
  right: 0,
  display: "flex",
  height: "100%",
  padding: "px1",
  gap: "px1",
});

const propertyStyle = css({
  display: "block",
});

const iconButtonStyle = css({
  minWidth: "24px",
  height: "100%",
  margin: 0,
  border: "none",
  padding: 0,
  backgroundColor: "transparent",
});

const iconStyle = css({
  display: "block",
  width: "100%",
  height: "100%",
  backgroundPosition: "center center",
  backgroundRepeat: "no-repeat",
  backgroundSize: "14px",
  filter: "var(--filter-icon)",
});

export default function VHeaderBar({ children }: PropsWithChildren) {
  const { t } = useTranslation();
  const { windowName } = useWindowNameStore();
  const [settings, setSettings] = useState<Settings | null>(null);
  const [showNSFW, setShowNSFW] = useState(false);

  useEffect(() => {
    let mounted = true;
    void IPC.settings.get().then((value) => {
      if (mounted) {
        setSettings(value);
      }
    });
    void IPC.nsfw.get().then((value) => {
      if (mounted) {
        setShowNSFW(value);
      }
    });

    const settingsSubscription = IPC.settings.on("update", (_event, value) => {
      setSettings(value);
    });
    const nsfwSubscription = IPC.common.on("showNSFW", (_event, value) => {
      setShowNSFW(value);
    });

    return () => {
      mounted = false;
      settingsSubscription.off();
      nsfwSubscription.off();
    };
  }, []);

  const visible = useMemo(() => {
    return (
      windowName.value === "board" ||
      windowName.value === "details" ||
      windowName.value === "browser" ||
      windowName.value === "capture"
    );
  }, [windowName.value]);

  async function toggleNSFW() {
    if (!showNSFW) {
      const result = await IPC.modals.open(t("utilsBar.nsfwConfirm"), [
        t("commons.yes"),
        t("commons.no"),
      ]);
      if (result === 0) {
        await IPC.nsfw.set(true);
      }
    } else {
      await IPC.nsfw.set(false);
    }
  }

  return (
    <div className={cx(rootStyle, windowName.value === "board" && shadowStyle)}>
      <div className={propertyStyle}>{children}</div>
      {visible ? (
        <>
          <div className={leftGroupStyle}>
            {windowName.value !== "board" ? (
              <HeaderButton icon={BoardIcon} onClick={() => IPC.windows.open("board")} />
            ) : null}
            {windowName.value !== "browser" ? (
              <HeaderButton icon={BrowserIcon} onClick={() => IPC.windows.open("browser")} />
            ) : null}
            {windowName.value !== "details" ? (
              <HeaderButton icon={ImportFileIcon} onClick={() => IPC.importer.browse("files")} />
            ) : null}
            {windowName.value !== "details" ? (
              <HeaderButton
                icon={ImportFolderIcon}
                onClick={() => IPC.importer.browse("directories")}
              />
            ) : null}
            {windowName.value !== "details" && settings?.web ? (
              <HeaderButton icon={WebIcon} onClick={() => IPC.windows.open("web")} />
            ) : null}
          </div>
          <div className={rightGroupStyle}>
            <HeaderButton icon={showNSFW ? NSFWIcon : SFWIcon} onClick={() => void toggleNSFW()} />
            <HeaderButton icon={SettingsIcon} onClick={() => IPC.windows.open("settings")} />
          </div>
        </>
      ) : null}
    </div>
  );

  function HeaderButton({ icon, onClick }: { icon: string; onClick: () => void }) {
    return (
      <button className={cx(appButtonStyle, iconButtonStyle)} onClick={onClick} tabIndex={-1} type="button">
        <span className={iconStyle} style={{ backgroundImage: `url(${icon})` }} />
      </button>
    );
  }
}

// src/renderer/components/commons/headerBar/VHeaderBar.vue
<template>
  <e-utils-bar-root
    :class="{
      shadow: windowName === 'board',
    }">
    <e-property>
      <slot></slot>
    </e-property>
    <e-commons class="left" v-if="visible">
      <button
        v-if="windowName !== 'board'"
        tabindex="-1"
        @click="openBoard()"
        @pointerenter="components.tooltip.open(t('tooltip.openBoard'), $event)">
        <e-icon class="board"></e-icon>
      </button>
      <button
        v-if="windowName !== 'browser'"
        tabindex="-1"
        @click="openBrowser()"
        @pointerenter="components.tooltip.open(t('tooltip.openBrowser'), $event)">
        <e-icon class="browser"></e-icon>
      </button>
      <button
        v-if="windowName !== 'details'"
        tabindex="-1"
        @click="browseAndImportFiles()"
        @pointerenter="components.tooltip.open(t('tooltip.importFiles'), $event)">
        <e-icon class="import-file"></e-icon>
      </button>
      <button
        v-if="windowName !== 'details'"
        tabindex="-1"
        @click="importImageDirectories()"
        @pointerenter="components.tooltip.open(t('tooltip.importFolders'), $event)">
        <e-icon class="import-folder"></e-icon>
      </button>
      <button
        v-if="windowName !== 'details' && settingsStore.state.value.web"
        tabindex="-1"
        @click="openWeb()"
        @pointerenter="components.tooltip.open(t('tooltip.importFromSP'), $event)">
        <e-icon class="web"></e-icon>
      </button>
      <!-- <button v-if="windowName !== 'capture'" tabindex="-1" @click="openCapture()">
        <e-icon class="import-folder"></e-icon>
      </button> -->
    </e-commons>
    <e-commons class="right" v-if="visible">
      <button
        tabindex="-1"
        @click="toggleNSFW"
        @pointerenter="components.tooltip.open(t('tooltip.toggleNSFW'), $event)">
        <e-icon :class="nsfwClass"></e-icon>
      </button>
      <button
        tabindex="-1"
        @click="openSettings"
        @pointerenter="components.tooltip.open(t('tooltip.openSettings'), $event)">
        <e-icon class="settings"></e-icon>
      </button>
    </e-commons>
  </e-utils-bar-root>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { useI18n } from "vue-i18n";

import { vec2FromPointerEvent } from "@/commons/utils/vec2";

import { IPC } from "@/renderer/libs/ipc";
import { useComponentsStore } from "@/renderer/stores/componentsStore/useComponentsStore";
import { useNSFWStore } from "@/renderer/stores/nsfwStore/useNSFWStore";
import { useSettingsStore } from "@/renderer/stores/settingsStore/useSettingsStore";
import { useWindowNameStore } from "@/renderer/stores/windowNameStore/useWindowNameStore";

const nsfwStore = useNSFWStore();
const components = useComponentsStore();
const { t } = useI18n();
const { windowName } = useWindowNameStore();
const settingsStore = useSettingsStore();
function openBoard() {
  IPC.windows.open("board");
}
function openBrowser() {
  IPC.windows.open("browser");
}
function openSettings() {
  IPC.windows.open("settings");
}
function openCapture() {
  IPC.windows.open("capture");
}
function openWeb() {
  IPC.windows.open("web");
}
function browseAndImportFiles() {
  IPC.importer.browse("files");
}
function importImageDirectories() {
  IPC.importer.browse("directories");
}
async function toggleNSFW() {
  if (!nsfwStore.state.value) {
    if (
      (await IPC.modals.open(t("utilsBar.nsfwConfirm"), [t("commons.yes"), t("commons.no")])) === 0
    ) {
      nsfwStore.update(true);
    }
  } else {
    nsfwStore.update(false);
  }
}
const visible = computed(() => {
  return (
    windowName.value === "board" ||
    windowName.value === "details" ||
    windowName.value === "browser" ||
    windowName.value === "capture"
  );
});
const nsfwClass = computed(() => {
  return nsfwStore.state.value ? "nsfw" : "sfw";
});
</script>

<style lang="scss" scoped>
e-utils-bar-root {
  --top-draggable-height: 10px;
  display: block;
  position: relative;
  z-index: 2;
  background-color: var(--color-0);
  width: 100%;
  min-height: 30px;
  &.shadow {
    box-shadow: 0px 1px 1px 0px rgba(0, 0, 0, 0.3);
  }
  > e-commons {
    display: flex;
    position: absolute;
    top: 0px;
    flex-shrink: 1;
    justify-content: flex-end;
    padding: var(--px-1);
    height: 100%;
    text-align: left;
    &.left {
      left: 0px;
      button {
        margin-right: var(--px-1);
      }
    }
    &.right {
      right: 0px;
      button {
        margin-left: var(--px-1);
      }
    }
    &.left,
    &.right {
      > button {
        margin: 0px;
        border: none;
        padding: 0px;
        min-width: 24px;
        height: 100%;
        > e-icon {
          display: block;
          filter: var(--filter-icon);
          background-position: center center;
          background-size: 14px;
          background-repeat: no-repeat;
          width: 100%;
          height: 100%;
          &.board {
            background-image: url("/images/icons/board.png");
          }
          &.browser {
            background-image: url("/images/icons/browser.png");
          }
          &.import-file {
            background-image: url("/images/icons/importFile.png");
          }
          &.import-folder {
            background-image: url("/images/icons/importFolder.png");
          }
          &.web {
            background-image: url("/images/icons/web.png");
          }
          &.settings {
            background-image: url("/images/icons/settings.png");
          }
          &.nsfw {
            background-image: url("/images/icons/nsfw.png");
          }
          &.sfw {
            background-image: url("/images/icons/sfw.png");
          }
          &.info {
            background-image: url("/images/icons/info.png");
          }
        }
      }
    }
  }
  > e-property {
    display: block;
  }
}
</style>
