// src/renderer/components/pageDownloader/VPageDownloader.vue
<template>
  <e-page-downloader-root>
    <e-image v-for="image in images" :key="image.url">
      <VSelectableBox :selected="image.selected" :zoom="true">
        <template #content>
          <e-content @click="click(image)" v-if="!image.error">
            <img
              :src="image.cacheURL"
              @load="loaded(image, $event.target as HTMLImageElement)"
              @error="error(image)"
              loading="lazy"
              decoding="async" />
          </e-content>
        </template>
        <template #inner>
          <e-inner>
            <e-size v-if="image.size"> {{ image.size.width }} x {{ image.size.height }} </e-size>
            <e-error v-if="image.error">error</e-error>
          </e-inner>
        </template>
      </VSelectableBox>
    </e-image>
  </e-page-downloader-root>
</template>

<script setup lang="ts">
import { onMounted, ref } from "vue";

import VSelectableBox from "../commons/utils/selectableBox/VSelectableBox.vue";

import { PageDownloaderData } from "@/commons/datas/pageDownloaderData";
import { PROTOCOLS } from "@/commons/defines";

import { IPC } from "@/renderer/libs/ipc";

type Data = Omit<PageDownloaderData, "urls" | "referer"> & {
  url: string;
  selected: boolean;
  cacheURL: string;
  size: { width: number; height: number };
  error: boolean;
};
const images = ref<Data[]>([]);
onMounted(async () => {
  IPC.pageDownloader.on("update", (_, urls) => {
    order(urls);
  });
  order(await IPC.downloader.getAll());
});
function loaded(data: Data, img: HTMLImageElement) {
  data.size = {
    width: img.naturalWidth,
    height: img.naturalWidth,
  };
}
function error(data: Data) {
  data.error = true;
}
function click(data: Data) {
  console.log(data);
  IPC.importer.import([
    [
      {
        type: "url",
        additionalData: {
          name: data.pageTitle,
          note: data.pageURL,
        },
        url: data.cacheURL,
      },
    ],
  ]);
}
function order(datas: PageDownloaderData[]) {
  datas.forEach((data) => {
    data.urls.forEach((url) => {
      images.value.unshift({
        cacheURL: url.startsWith("data")
          ? url
          : `${PROTOCOLS.FILE.PAGE_DOWNLOADER_CACHE}://?url=${encodeURIComponent(url)}&referer=${encodeURIComponent(data.referer)}`,
        pageTitle: data.pageTitle,
        pageURL: data.pageURL,
        url,
        selected: false,
        error: false,
        size: { width: 0, height: 0 },
      });
    });
  });
}
</script>

<style lang="scss" scoped>
e-page-downloader-root {
  display: flex;
  flex-wrap: wrap;
  gap: var(--px-2);
  will-change: scroll-position;
  padding: 0px;
  width: 100%;
  height: 100%;
  overflow-y: auto;
  > e-image {
    display: block;
    width: 300px;
    height: 300px;
    e-content {
      display: block;
      width: 100%;
      height: 100%;
      > img {
        width: 100%;
        height: 100%;
        object-fit: contain;
      }
    }
    e-inner {
      display: block;
      position: relative;
      width: 100%;
      height: 100%;
      > e-size,
      e-error {
        display: block;
        position: absolute;
        margin-top: var(--px-0);
        margin-left: var(--px-0);
        border-radius: var(--rounded);
        background-color: var(--color-1);
        padding: var(--px-0);
      }
      > e-error {
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
      }
    }
  }
}
</style>

// src/renderer/components/pageDownloader/VPageDownloader.tsx
import { useEffect, useState } from "react";
import { css } from "styled-system/css";

import { PageDownloaderData } from "@/commons/datas/pageDownloaderData";
import { PROTOCOLS } from "@/commons/defines";

import VSelectableBox from "@/renderer/components/commons/utils/selectableBox/VSelectableBox";
import { IPC } from "@/renderer/libs/ipc";

type DownloadImage = Omit<PageDownloaderData, "urls" | "referer"> & {
  id: string;
  cacheURL: string;
  error: boolean;
  selected: boolean;
  size: { height: number; width: number } | null;
  url: string;
};

const rootStyle = css({
  display: "flex",
  flexWrap: "wrap",
  gap: "px2",
  width: "100%",
  height: "100%",
  overflowY: "auto",
});

const imageStyle = css({
  display: "block",
  width: "300px",
  height: "300px",
  flexShrink: 0,
});

const imageContentStyle = css({
  display: "block",
  width: "100%",
  height: "100%",
  border: "none",
  background: "transparent",
  padding: 0,
});

const imageElementStyle = css({
  width: "100%",
  height: "100%",
  objectFit: "contain",
});

const innerStyle = css({
  position: "relative",
  width: "100%",
  height: "100%",
});

const badgeStyle = css({
  position: "absolute",
  top: "px0",
  left: "px0",
  borderRadius: "window",
  backgroundColor: "surfaceEmphasis",
  paddingX: "px1",
  paddingY: "px0",
  fontSize: "size0",
  lineHeight: "size0",
});

const errorStyle = css({
  position: "absolute",
  top: "50%",
  left: "50%",
  transform: "translate(-50%, -50%)",
  borderRadius: "window",
  backgroundColor: "surfaceEmphasis",
  paddingX: "px1",
  paddingY: "px0",
  fontSize: "size0",
  lineHeight: "size0",
});

function normalizePageDownloaderDatas(datas: PageDownloaderData[]) {
  const images: DownloadImage[] = [];
  datas.forEach((data) => {
    data.urls.forEach((url) => {
      images.unshift({
        id: `${data.pageURL}::${url}`,
        cacheURL: url.startsWith("data")
          ? url
          : `${PROTOCOLS.FILE.PAGE_DOWNLOADER_CACHE}://?url=${encodeURIComponent(url)}&referer=${encodeURIComponent(data.referer)}`,
        pageTitle: data.pageTitle,
        pageURL: data.pageURL,
        url,
        selected: false,
        error: false,
        size: null,
      });
    });
  });
  return images;
}

export default function VPageDownloader() {
  const [images, setImages] = useState<DownloadImage[]>([]);

  useEffect(() => {
    let mounted = true;

    const refresh = async () => {
      const datas = await IPC.downloader.getAll();
      if (!mounted) {
        return;
      }
      setImages(normalizePageDownloaderDatas(datas));
    };

    void refresh();
    const subscription = IPC.pageDownloader.on("update", () => {
      void refresh();
    });

    return () => {
      mounted = false;
      subscription.off();
    };
  }, []);

  function loaded(id: string, img: HTMLImageElement) {
    setImages((current) =>
      current.map((image) =>
        image.id === id
          ? {
              ...image,
              size: {
                width: img.naturalWidth,
                height: img.naturalHeight,
              },
            }
          : image,
      ),
    );
  }

  function error(id: string) {
    setImages((current) =>
      current.map((image) => (image.id === id ? { ...image, error: true } : image)),
    );
  }

  function click(image: DownloadImage) {
    void IPC.importer.import([
      [
        {
          type: "url",
          additionalData: {
            name: image.pageTitle,
            note: image.pageURL,
          },
          url: image.cacheURL,
        },
      ],
    ]);
  }

  return (
    <div className={rootStyle}>
      {images.map((image) => (
        <div className={imageStyle} key={image.id}>
          <VSelectableBox
            inner={
              <div className={innerStyle}>
                {image.size ? (
                  <div className={badgeStyle}>
                    {image.size.width} x {image.size.height}
                  </div>
                ) : null}
                {image.error ? <div className={errorStyle}>error</div> : null}
              </div>
            }
            selected={image.selected}
            zoom>
            {!image.error ? (
              <button className={imageContentStyle} onClick={() => click(image)} type="button">
                <img
                  className={imageElementStyle}
                  decoding="async"
                  loading="lazy"
                  onError={() => error(image.id)}
                  onLoad={(event) => loaded(image.id, event.currentTarget)}
                  src={image.cacheURL}
                />
              </button>
            ) : null}
          </VSelectableBox>
        </div>
      ))}
    </div>
  );
}
