// src/renderer/components/commons/playbackController/VSeekBar.vue
<template>
  <e-seekbar-root>
    <e-cursor-wrapper ref="root">
      <e-seek>
        <e-cursor
          :style="{
            left: `${cursorPosition}%`,
          }">
        </e-cursor>
      </e-seek>
      <e-loop>
        <e-cursor
          @pointerdown="pointerMove($event, `seek`)"
          :style="{
            left: `${(props.loopStart === 0 && props.loopEnd === 0 ? 0 : props.loopStart / props.duration) * 100}%`,
            width: `${(props.loopStart === 0 && props.loopEnd === 0 ? 1 : (props.loopEnd - props.loopStart) / props.duration) * 100}%`,
          }">
        </e-cursor>
        <!-- start -->
        <e-drag
          @pointerdown="pointerMove($event, `loopStart`)"
          :style="{ left: `${(props.loopStart / props.duration) * 100}%` }"
          class="left"></e-drag>
        <!-- end -->
        <e-drag
          @pointerdown="pointerMove($event, `loopEnd`)"
          :style="{
            left: `${((props.loopStart === 0 && props.loopEnd === 0 ? props.duration : props.loopEnd) / props.duration) * 100}%`,
          }"
          class="right"></e-drag>
      </e-loop>
    </e-cursor-wrapper>
  </e-seekbar-root>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from "vue";

const props = defineProps<{
  duration: number;
  time: number;
  loopStart: number;
  loopEnd: number;
}>();
const emit = defineEmits<{
  (e: "update:time", time: number): void;
  (e: "update:loopStart", time: number): void;
  (e: "update:loopEnd", time: number): void;
  (e: "startSeek"): void;
  (e: "stopSeek"): void;
}>();
const root = ref<HTMLElement>();
const draggingTime = ref(0);
const draggingType = ref<"loopStart" | "loopEnd" | "seek" | "none">("none");
onMounted(() => {
  window.addEventListener("pointerup", pointerMove);
  window.addEventListener("pointermove", pointerMove);
});
function pointerMove(event: PointerEvent, type?: typeof draggingType.value) {
  if (event.type === "pointerdown") {
    if (type !== undefined) {
      draggingType.value = type;
    }
    if (draggingType.value === "seek") {
      emit("startSeek");
    }
  }
  if (draggingType.value === "none") {
    return;
  }
  if (event.type === "pointerup") {
    if (draggingType.value === "seek") {
      emit("stopSeek");
    }
    draggingType.value = "none";
  }
  const rect = root.value?.getBoundingClientRect();
  if (rect === undefined) {
    return;
  }
  const x = event.clientX - rect.x;
  let time = (x / rect.width) * props.duration;
  if (time < 0) {
    time = 0;
  } else if (time > props.duration) {
    time = props.duration;
  }
  if (draggingType.value === "seek") {
    draggingTime.value = time;
    emit("update:time", draggingTime.value);
  } else if (draggingType.value === "loopStart") {
    emit("update:loopStart", time);
  } else if (draggingType.value === "loopEnd") {
    emit("update:loopEnd", time);
  }
}
const cursorPosition = computed(() => {
  const time =
    ((draggingType.value === "seek" ? draggingTime.value : props.time) / props.duration) * 100;
  if (time < 0) {
    return 0;
  } else if (time > 100) {
    return 100;
  }
  return time;
});
</script>

<style lang="scss" scoped>
e-seekbar-root {
  display: block;
  position: relative;
  cursor: pointer;
  border-radius: var(--rounded);
  background-color: var(--color-0);
  padding: var(--px-2) calc(var(--px-2) + calc(var(--px-1) / 2));
  width: 100%;
  height: 32px;
  overflow: hidden;
  > e-cursor-wrapper {
    display: block;
    position: relative;
    width: 100%;
    height: 100%;
    > e-loop {
      display: block;
      position: absolute;
      top: 0px;
      left: 0px;
      // opacity: 0.5;
      z-index: 1;
      width: 100%;
      height: 100%;
      > e-cursor {
        display: block;
        position: relative;
        top: 0px;
        left: 0px;
        opacity: 0.1;
        border-radius: var(--rounded);
        background-color: var(--color-font);
        height: 100%;
      }
      > e-drag {
        display: block;
        position: absolute;
        top: 0px;
        left: 0px;
        border-radius: var(--rounded);
        background-color: var(--color-accent-1);
        width: var(--px-1);
        height: 100%;
        &.left {
          transform: translateX(-100%);
        }
        &.right {
          transform: translateX(0%);
        }
      }
    }
    > e-seek {
      display: block;
      position: absolute;
      top: 0px;
      left: 0px;
      z-index: 0;
      width: 100%;
      height: 100%;
      > e-cursor {
        display: block;
        position: absolute;
        transform: translateX(-50%);
        border-radius: var(--rounded);
        background-color: var(--color-font);
        width: var(--px-1);
        height: 100%;
      }
    }
  }
}
</style>

// src/renderer/components/commons/playbackController/VSeekBar.tsx
import { PointerEvent as ReactPointerEvent, useEffect, useMemo, useRef, useState } from "react";
import { css } from "styled-system/css";

const rootStyle = css({
  position: "relative",
  display: "block",
  overflow: "hidden",
  width: "100%",
  height: "32px",
  paddingY: "px2",
  paddingX: "calc(var(--px-2) + calc(var(--px-1) / 2))",
  borderRadius: "window",
  backgroundColor: "surface",
});

const wrapperStyle = css({
  position: "relative",
  width: "100%",
  height: "100%",
});

const layerStyle = css({
  position: "absolute",
  inset: 0,
});

const loopCursorStyle = css({
  position: "relative",
  display: "block",
  height: "100%",
  borderRadius: "window",
  backgroundColor: "text",
  opacity: 0.1,
});

const dragHandleStyle = css({
  position: "absolute",
  top: 0,
  left: 0,
  display: "block",
  width: "px1",
  height: "100%",
  borderRadius: "window",
  backgroundColor: "accent",
});

const seekCursorStyle = css({
  position: "absolute",
  display: "block",
  width: "px1",
  height: "100%",
  transform: "translateX(-50%)",
  borderRadius: "window",
  backgroundColor: "text",
});

function clamp(value: number, min: number, max: number) {
  return Math.min(Math.max(value, min), max);
}

export default function VSeekBar({
  duration,
  loopEnd,
  loopStart,
  onLoopEndChange,
  onLoopStartChange,
  onSeekStart,
  onSeekStop,
  onTimeChange,
  time,
}: {
  duration: number;
  loopEnd: number;
  loopStart: number;
  onLoopEndChange: (time: number) => void;
  onLoopStartChange: (time: number) => void;
  onSeekStart: () => void;
  onSeekStop: () => void;
  onTimeChange: (time: number) => void;
  time: number;
}) {
  const rootRef = useRef<HTMLDivElement>(null);
  const [draggingTime, setDraggingTime] = useState(0);
  const [draggingType, setDraggingType] = useState<"loopEnd" | "loopStart" | "none" | "seek">(
    "none",
  );

  function updateFromClientX(clientX: number, type: "loopEnd" | "loopStart" | "seek") {
    const rect = rootRef.current?.getBoundingClientRect();
    if (rect === undefined || duration <= 0) {
      return;
    }
    let nextTime = clamp(((clientX - rect.x) / rect.width) * duration, 0, duration);
    if (type === "seek") {
      setDraggingTime(nextTime);
      onTimeChange(nextTime);
    } else if (type === "loopStart") {
      if (nextTime > loopEnd) {
        nextTime = loopEnd;
      }
      onLoopStartChange(nextTime);
    } else if (type === "loopEnd") {
      if (nextTime < loopStart) {
        nextTime = loopStart;
      }
      onLoopEndChange(nextTime);
    }
  }

  useEffect(() => {
    function pointerMove(event: PointerEvent) {
      if (draggingType === "none") {
        return;
      }
      updateFromClientX(event.clientX, draggingType);
    }

    function pointerUp(event: PointerEvent) {
      if (draggingType === "none") {
        return;
      }
      pointerMove(event);
      if (draggingType === "seek") {
        onSeekStop();
      }
      setDraggingType("none");
    }

    window.addEventListener("pointermove", pointerMove);
    window.addEventListener("pointerup", pointerUp);
    return () => {
      window.removeEventListener("pointermove", pointerMove);
      window.removeEventListener("pointerup", pointerUp);
    };
  }, [
    draggingType,
    duration,
    loopEnd,
    loopStart,
    onLoopEndChange,
    onLoopStartChange,
    onSeekStop,
    onTimeChange,
  ]);

  const cursorPosition = useMemo(() => {
    if (duration <= 0) {
      return 0;
    }
    return clamp(((draggingType === "seek" ? draggingTime : time) / duration) * 100, 0, 100);
  }, [draggingTime, draggingType, duration, time]);

  const loopStartPosition = duration <= 0 ? 0 : ((loopStart === 0 && loopEnd === 0 ? 0 : loopStart) / duration) * 100;
  const loopWidth = duration <= 0 ? 0 : ((loopStart === 0 && loopEnd === 0 ? 1 : loopEnd - loopStart) / duration) * 100;
  const loopEndPosition = duration <= 0 ? 0 : (((loopStart === 0 && loopEnd === 0 ? duration : loopEnd)) / duration) * 100;

  function beginDrag(event: ReactPointerEvent<HTMLDivElement>, type: "loopEnd" | "loopStart" | "seek") {
    setDraggingType(type);
    if (type === "seek") {
      onSeekStart();
    }
    if (type === "loopStart" && loopStart === 0 && loopEnd === 0) {
      onLoopEndChange(duration);
    }
    updateFromClientX(event.clientX, type);
  }

  return (
    <div className={rootStyle}>
      <div className={wrapperStyle} ref={rootRef}>
        <div className={layerStyle}>
          <div className={loopCursorStyle} style={{ left: `${loopStartPosition}%`, width: `${loopWidth}%` }} />
          <div
            className={dragHandleStyle}
            onPointerDown={(event) => beginDrag(event, "loopStart")}
            style={{ left: `${loopStartPosition}%`, transform: "translateX(-100%)", cursor: "e-resize" }}
          />
          <div
            className={dragHandleStyle}
            onPointerDown={(event) => beginDrag(event, "loopEnd")}
            style={{ left: `${loopEndPosition}%`, cursor: "w-resize" }}
          />
        </div>
        <div className={layerStyle}>
          <div
            className={seekCursorStyle}
            onPointerDown={(event) => beginDrag(event, "seek")}
            style={{ left: `${cursorPosition}%` }}
          />
        </div>
      </div>
    </div>
  );
}
