// src/renderer/components/settings/VSettings.tsx
import { useEffect, useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import { css, cx } from "styled-system/css";

import { Settings } from "@/commons/datas/settings";

import VSettingsBrowser from "@/renderer/components/settings/VSettingsBrowser";
import VSettingsControl from "@/renderer/components/settings/VSettingsControl";
import VSettingsDatas from "@/renderer/components/settings/VSettingsDatas";
import VSettingsGeneral from "@/renderer/components/settings/VSettingsGeneral";
import VSettingsInfo from "@/renderer/components/settings/VSettingsInfo";
import VSettingsOthers from "@/renderer/components/settings/VSettingsOthers";
import VSettingsUpdate from "@/renderer/components/settings/VSettingsUpdate";
import VSettingsWeb from "@/renderer/components/settings/VSettingsWeb";
import { IPC } from "@/renderer/libs/ipc";

const rootStyle = css({
  display: "flex",
  flexDirection: "row",
  height: "100%",
  overflow: "hidden",
});

const categoriesStyle = css({
  paddingRight: "px2",
});

const categoryStyle = css({
  display: "block",
  marginBottom: "px2",
  cursor: "pointer",
});

const selectedCategoryStyle = css({
  textDecoration: "underline",
});

const contentsStyle = css({
  flex: 1,
  overflowX: "hidden",
  overflowY: "auto",
});

const tabNames = [
  "general",
  "control",
  "browser",
  "datas",
  "web",
  "others",
  "update",
  "info",
] as const;

type TabName = (typeof tabNames)[number];

export default function VSettings() {
  const { t } = useTranslation();
  const [currentTab, setCurrentTab] = useState<TabName>("general");
  const [settings, setSettings] = useState<Settings | null>(null);

  useEffect(() => {
    let mounted = true;
    void IPC.settings.get().then((value) => {
      if (mounted) {
        setSettings(value);
      }
    });

    const settingsSubscription = IPC.settings.on("update", (_event, value) => {
      setSettings(value);
    });
    const latestVersionSubscription = IPC.common.on("foundLatestVersion", () => {
      setCurrentTab("update");
    });

    void IPC.common.getLatestVersion().then((remoteBinaryInfo) => {
      if (!remoteBinaryInfo.isLatest) {
        setCurrentTab("update");
      }
    });

    return () => {
      mounted = false;
      settingsSubscription.off();
      latestVersionSubscription.off();
    };
  }, []);

  async function updateSettings(nextSettings: Settings) {
    setSettings(nextSettings);
    await IPC.settings.update(nextSettings);
  }

  const content = useMemo(() => {
    if (settings === null) {
      return null;
    }
    const onSettingsChange = (next: Settings) => void updateSettings(next);
    if (currentTab === "general") {
      return <VSettingsGeneral onSettingsChange={onSettingsChange} settings={settings} />;
    }
    if (currentTab === "control") {
      return <VSettingsControl onSettingsChange={onSettingsChange} settings={settings} />;
    }
    if (currentTab === "browser") {
      return <VSettingsBrowser onSettingsChange={onSettingsChange} settings={settings} />;
    }
    if (currentTab === "datas") {
      return <VSettingsDatas onSettingsChange={onSettingsChange} settings={settings} />;
    }
    if (currentTab === "web") {
      return <VSettingsWeb onSettingsChange={onSettingsChange} settings={settings} />;
    }
    if (currentTab === "others") {
      return <VSettingsOthers onSettingsChange={onSettingsChange} settings={settings} />;
    }
    if (currentTab === "update") {
      return <VSettingsUpdate />;
    }
    return <VSettingsInfo />;
  }, [currentTab, settings]);

  return (
    <div className={rootStyle}>
      <div className={categoriesStyle}>
        {tabNames.map((tab) => (
          <div
            className={cx(categoryStyle, currentTab === tab && selectedCategoryStyle)}
            key={tab}
            onClick={() => setCurrentTab(tab)}>
            {t(`settings.${tab}`)}
          </div>
        ))}
      </div>
      <div className={contentsStyle}>{content}</div>
    </div>
  );
}

// src/rendererProcess/components/settings/VSettings.vue
<template>
  <t-settings-root>
    <ul>
      <li
        v-for="tab in tabs"
        :key="tab"
        :class="{
          selected: currentTab === tab,
        }"
        @click="currentTab = tab"
      >
        {{ t("settings." + tab) }}
      </li>
    </ul>
    <t-contents>
      <!--
        General
      -->
      <t-content v-if="currentTab === 'general'">
        <VSettingsGeneral />
      </t-content>
      <!--
        Control
      -->
      <t-content v-if="currentTab === 'control'">
        <VSettingsControl />
      </t-content>
      <!--
        Browser
      -->
      <t-content v-if="currentTab === 'browser'">
        <VSettingsBrowser />
      </t-content>
      <!--
        Datas
      -->
      <t-content v-if="currentTab === 'datas'">
        <VSettingsDatas />
      </t-content>
      <!--
        Others
      -->
      <t-content v-if="currentTab === 'others'">
        <VSettingsOthers />
      </t-content>
      <!--
        Update
      -->
      <t-content v-if="currentTab === 'update'">
        <VSettingsUpdate />
      </t-content>
      <!--
        Info
      -->
      <t-content v-if="currentTab === 'info'">
        <VSettingsInfo />
      </t-content>
    </t-contents>
  </t-settings-root>
</template>

<script setup lang="ts">
// Vue
import { onMounted, ref } from "vue";
// Others
import { API } from "@/rendererProcess/api";
import { useI18n } from "vue-i18n";
import VSettingsGeneral from "@/rendererProcess/components/settings/VSettingsGeneral.vue";
import VSettingsDatas from "@/rendererProcess/components/settings/VSettingsDatas.vue";
import VSettingsOthers from "@/rendererProcess/components/settings/VSettingsOthers.vue";
import VSettingsUpdate from "@/rendererProcess/components/settings/VSettingsUpdate.vue";
import VSettingsInfo from "@/rendererProcess/components/settings/VSettingsInfo.vue";
import VSettingsControl from "@/rendererProcess/components/settings/VSettingsControl.vue";
import VSettingsBrowser from "@/rendererProcess/components/settings/VSettingsBrowser.vue";
const { t } = useI18n();
const tabNames = ["general", "control", "browser", "datas", "others", "update", "info"] as const;
const tabs = ref<typeof tabNames[number][]>([...tabNames]);
const currentTab = ref<typeof tabNames[number]>("general");
onMounted(async () => {
  API.on("foundLatestVersion", async () => {
    currentTab.value = "update";
  });
  const remoteBinaryInfo = await API.send("getLatestVersion");
  if (!remoteBinaryInfo.isLatest) {
    currentTab.value = "update";
  }
});
</script>

<style lang="scss" scoped>
t-settings-root {
  text-align: center;
  display: flex;
  flex-direction: column;
  height: 100%;
  overflow: hidden;
  > ul {
    list-style-type: none;
    padding: 0px;
    > li {
      margin: 0px 8px;
      display: inline-block;
      cursor: pointer;
      &.selected {
        text-decoration: underline;
      }
    }
  }
  > t-contents {
    height: 100%;
    overflow-y: scroll;
    overflow-x: hidden;
    display: block;
    > t-content {
      display: block;
    }
  }
}
</style>
