// src/renderer/components/settings/VSettingsInfo.tsx
import { useEffect, useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import { css } from "styled-system/css";

import { URL_SUPPORT } from "@/commons/defines";

import { appButtonStyle } from "@/renderer/components/shared/controlStyles";
import { IPC } from "@/renderer/libs/ipc";
import { useAppInfoStore } from "@/renderer/stores/appInfoStore/useAppInfoStore";

const rootStyle = css({
  display: "block",
  textAlign: "center",
});

const paragraphStyle = css({
  fontSize: "size1",
  wordBreak: "break-word",
});

const preStyle = css({
  overflow: "hidden",
  fontSize: "size0",
  whiteSpace: "pre-wrap",
});

const leftAlignedPreStyle = css({
  textAlign: "left",
});

export default function VSettingsInfo() {
  const { t } = useTranslation();
  const appInfoStore = useAppInfoStore();
  const appInfo = appInfoStore.state.value;
  const [licenses, setLicenses] = useState<{ licenses: string; name: string; text: string }[]>([]);
  const [supporters, setSupporters] = useState<{ names: string[]; type: string }[]>([]);

  useEffect(() => {
    let mounted = true;
    void Promise.all([IPC.common.getLicenses(), IPC.common.getSupporters()]).then(
      ([licenseValues, supporterValues]) => {
        if (!mounted) {
          return;
        }
        setLicenses(licenseValues);
        setSupporters(
          Object.keys(supporterValues).map((type) => ({
            type,
            names: supporterValues[type],
          })),
        );
      },
    );
    return () => {
      mounted = false;
    };
  }, []);

  const supporterText = useMemo(
    () =>
      supporters
        .map((data) => `--${data.type}--\n${data.names.join("\n")}`)
        .join("\n\n"),
    [supporters],
  );

  const licenseText = useMemo(
    () => licenses.map((license) => `${license.name}\n${license.licenses}\n${license.text}`).join("\n"),
    [licenses],
  );

  function gotoGithub() {
    void IPC.common.openURL("https://github.com/takumus/ImagePetaPeta");
  }

  function gotoIssues() {
    void IPC.common.openURL(
      `${URL_SUPPORT}?usp=pp_url&entry.1709939184=${encodeURIComponent(appInfo.version)}`,
    );
  }

  function gotoIcons8() {
    void IPC.common.openURL("https://icons8.com/");
  }

  function showDBFolder() {
    void IPC.common.showDBFolder();
  }

  function showConfigFolder() {
    void IPC.common.showConfigFolder();
  }

  function showEULA() {
    void IPC.windows.open("eula");
  }

  return (
    <div className={rootStyle}>
      <p className={paragraphStyle}>
        {appInfo.name} {appInfo.version}
      </p>
      <p className={paragraphStyle}>Electron {appInfo.electronVersion}</p>
      <p className={paragraphStyle}>Chromium {appInfo.chromiumVersion}</p>
      <p className={paragraphStyle}>Node.js {appInfo.nodeVersion}</p>
      <button className={appButtonStyle} onClick={gotoGithub} type="button">
        {t("info.githubButton")}
      </button>
      <button className={appButtonStyle} onClick={gotoIssues} type="button">
        {t("info.issuesButton")}
      </button>
      <p />
      <button className={appButtonStyle} onClick={showDBFolder} type="button">
        {t("info.dbFolderButton")}
      </button>
      <button className={appButtonStyle} onClick={showConfigFolder} type="button">
        {t("info.configFolderButton")}
      </button>
      <p />
      <button className={appButtonStyle} onClick={showEULA} type="button">
        {t("info.showEULAButton")}
      </button>
      <p className={paragraphStyle}>{t("info.assets")}</p>
      <button className={appButtonStyle} onClick={gotoIcons8} type="button">
        Icons8.com
      </button>
      <p className={paragraphStyle}>{t("info.supporters")}</p>
      <pre className={preStyle}>{supporterText}</pre>
      <p className={paragraphStyle}>{t("info.licenses")}</p>
      <pre className={`${preStyle} ${leftAlignedPreStyle}`}>{licenseText}</pre>
    </div>
  );
}

// src/rendererProcess/components/settings/VSettingsInfo.vue
<template>
  <t-settings-content-root class="info">
    <p>{{ appInfoStore.state.value.name }} {{ appInfoStore.state.value.version }}</p>
    <button tabindex="-1" @click="gotoGithub">
      {{ t("info.githubButton") }}
    </button>
    <button tabindex="-1" @click="gotoIssues">
      {{ t("info.issuesButton") }}
    </button>
    <p></p>
    <button tabindex="-1" @click="showDBFolder">
      {{ t("info.dbFolderButton") }}
    </button>
    <button tabindex="-1" @click="showConfigFolder">
      {{ t("info.configFolderButton") }}
    </button>
    <p></p>
    <button tabindex="-1" @click="showEULA">
      {{ t("info.showEULAButton") }}
    </button>
    <p>{{ t("info.assets") }}</p>
    <button tabindex="-1" @click="gotoIcons8">Icons8.com</button>
    <p>{{ t("info.debuggers") }}</p>
    <pre class="debuggers">{{ debuggers }}</pre>
    <p>{{ t("info.licenses") }}</p>
    <pre class="licenses">{{ licenses }}</pre>
  </t-settings-content-root>
</template>

<script setup lang="ts">
// Others
import { IPC } from "@/rendererProcess/ipc";
import { useI18n } from "vue-i18n";
import { useAppInfoStore } from "@/rendererProcess/stores/appInfoStore";
import { SUPPORT_URL } from "@/commons/defines";
import { LICENSES } from "@/@assets/licenses";
import { DEBUGGERS } from "@/@assets/debuggers";
import { computed } from "vue";
import { WindowType } from "@/commons/datas/windowType";
const { t } = useI18n();
const appInfoStore = useAppInfoStore();
const licenses = computed(() => {
  return LICENSES.map((lib) => `${lib.name}\n${lib.licenses}\n`).join("\n");
});
const debuggers = computed(() => {
  return DEBUGGERS.join(", ");
});
function gotoGithub() {
  IPC.send("openURL", "https://github.com/takumus/ImagePetaPeta");
}
function gotoIssues() {
  IPC.send(
    "openURL",
    `${SUPPORT_URL}?usp=pp_url&entry.1709939184=${encodeURIComponent(
      appInfoStore.state.value.version,
    )}`,
  );
}
function gotoIcons8() {
  IPC.send("openURL", "https://icons8.com/");
}
function showDBFolder() {
  IPC.send("showDBFolder");
}
function showConfigFolder() {
  IPC.send("showConfigFolder");
}
function showEULA() {
  IPC.send("openWindow", WindowType.EULA);
}
</script>

<style lang="scss" scoped>
t-settings-content-root.info {
  text-align: center;
  display: block;
  > pre {
    &.licenses {
      text-align: left;
    }
    &.debuggers {
      text-align: center;
    }
    overflow: hidden;
    white-space: pre-wrap;
    font-size: var(--size-0);
  }
  > p {
    font-size: var(--size-1);
    word-break: break-word;
  }
}
</style>
<style lang="scss" scoped>
@import "@/rendererProcess/components/settings/index.scss";
</style>
