// src/renderer/components/commons/utils/checkbox/VCheckbox.tsx
import { css, cx } from "styled-system/css";

const rootStyle = css({
  display: "inline-block",
  border: "none",
  margin: 0,
  background: "transparent",
  padding: "px1",
  height: "23px",
  color: "inherit",
  cursor: "pointer",
});

const disabledStyle = css({
  cursor: "not-allowed",
  opacity: 0.56,
});

const trackStyle = css({
  position: "relative",
  display: "block",
  overflow: "hidden",
  height: "100%",
  aspectRatio: "2",
  borderRadius: "window",
  backgroundColor: "checkboxFalseBackground",
  transitionDuration: "100ms",
});

const trackCheckedStyle = css({
  backgroundColor: "checkboxTrueBackground",
});

const thumbStyle = css({
  position: "relative",
  left: "0%",
  display: "block",
  height: "100%",
  aspectRatio: "1",
  transform: "scale(0.7)",
  borderRadius: "circle",
  backgroundColor: "checkboxFalseCircle",
  boxShadow: "0px 0.5px 2px rgba(0, 0, 0, 0.2)",
  transitionDuration: "100ms",
  transitionProperty: "left, background-color",
});

const thumbCheckedStyle = css({
  left: "50%",
  backgroundColor: "checkboxTrueCircle",
});

export default function VCheckbox({
  disabled = false,
  value,
  onValueChange,
}: {
  disabled?: boolean;
  value: boolean;
  onValueChange: (value: boolean) => void;
}) {
  return (
    <button
      aria-checked={value}
      className={cx(rootStyle, disabled && disabledStyle)}
      disabled={disabled}
      onClick={() => {
        if (!disabled) {
          onValueChange(!value);
        }
      }}
      role="switch"
      type="button">
      <span className={cx(trackStyle, value && trackCheckedStyle)}>
        <span className={cx(thumbStyle, value && thumbCheckedStyle)} />
      </span>
    </button>
  );
}

// src/renderer/components/commons/utils/checkbox/VCheckbox.vue
<template>
  <t-checkbox-root @click="click">
    <t-content :class="{ checked: value }">
      <t-circle> </t-circle>
    </t-content>
  </t-checkbox-root>
</template>

<script setup lang="ts">
const props = defineProps<{
  value: boolean;
}>();
const emit = defineEmits<{
  (e: "update:value", value: boolean): void;
}>();
function click() {
  emit("update:value", !props.value);
}
</script>

<style lang="scss" scoped>
t-checkbox-root {
  display: inline-block;
  height: 26px;
  padding: var(--px-1);
  cursor: pointer;
  > t-content {
    display: block;
    height: 100%;
    aspect-ratio: 2;
    border-radius: 999px;
    position: relative;
    background-color: var(--color-checkbox-false-background);
    overflow: hidden;
    > t-circle {
      display: block;
      border-radius: 999px;
      background-color: var(--color-checkbox-false-circle);
      height: 100%;
      aspect-ratio: 1;
      transform: scale(0.7);
      position: relative;
      transition-duration: 100ms;
      transition-property: left, background-color;
      left: 0%;
      box-shadow: 0px 0.5px 2px rgba(0, 0, 0, 0.2);
    }
    &.checked {
      background-color: var(--color-checkbox-true-background);
      > t-circle {
        left: 50%;
        background-color: var(--color-checkbox-true-circle);
      }
    }
  }
}
</style>
